/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "analysis.h"
#include "checks_mem.h"
#include "checks_sec.h"
#include "checks_syntax.h"
#include "checks_types.h"
#include "checks_perf.h"
#include "checks_concurrency.h"
#include "checks_quality.h"
#include "checks_buf.h"
#include "checks_c.h"
#include "checks_cpp.h"
#include "checks_csharp.h"
#include "checks_java.h"
#include "checks_js.h"
#include "checks_ts.h"
#include "checks_python.h"
#include "checks_ruby.h"
#include "checks_php.h"
#include "checks_go.h"
#include "checks_rust.h"
#include "checks_swift.h"
#include "checks_kotlin.h"
#include "checks_scala.h"
#include "checks_dart.h"
#include "checks_haskell.h"
#include "checks_lua.h"
#include "checks_r.h"
#include "checks_julia.h"
#include "checks_perl.h"
#include "checks_shell.h"
#include "checks_sql.h"
#include "checks_html.h"
#include "checks_css.h"
#include "checks_yaml.h"
#include "checks_objectivec.h"
#include "checks_groovy.h"
#include "checks_fortran.h"
#include "checks_cobol.h"
#include "checks_basic.h"
#include "checks_pascal.h"
#include "checks_ada.h"
#include "checks_lisp.h"
#include "checks_prolog.h"
#include "checks_erlang.h"
#include "checks_elixir.h"
#include "checks_clojure.h"
#include "checks_fsharp.h"
#include "checks_visualbasic.h"
#include "checks_powershell.h"
#include "checks_matlab.h"
#include "checks_d.h"
#include "checks_dockerfile.h"
#include "checks_json.h"
#include "checks_toml.h"
#include "checks_cmake.h"
#include "checks_makefile.h"
#include "checks_tex.h"
#include "checks_vue.h"
#include "checks_svelte.h"
#include "checks_solidity.h"
#include "checks_graphql.h"
#include "checks_tcl.h"
#include "checks_coffeescript.h"
#include "checks_nim.h"
#include "checks_zig.h"
#include "checks_ocaml.h"
#include "checks_purescript.h"
#include "checks_racket.h"
#include "checks_scheme.h"
#include "checks_verilog.h"
#include "checks_vhdl.h"
#include "checks_vala.h"
#include "checks_thrift.h"
#include "checks_smalltalk.h"
#include "checks_apl.h"
#include "checks_awk.h"
#include "checks_forth.h"
#include "checks_idl.h"
#include "checks_opencl.h"
#include "checks_openscad.h"
#include "checks_protobuf.h"
#include "checks_sas.h"
#include "checks_stata.h"
#include "checks_viml.h"
Engine*engine_init(int threads){Engine*e=calloc(1,sizeof(Engine));if(!e)return NULL;e->cap=512;e->checks=calloc(e->cap,sizeof(Check));e->nchecks=0;e->check_counts=calloc(e->cap,sizeof(int));e->check_times=calloc(e->cap,sizeof(double));e->total_issues=0;e->threads=threads>0?threads:1;e->verbose=0;return e;}
void engine_register_check(Engine*e,Check c){if(e->nchecks>=e->cap){e->cap*=2;e->checks=realloc(e->checks,e->cap*sizeof(Check));e->check_counts=realloc(e->check_counts,e->cap*sizeof(int));e->check_times=realloc(e->check_times,e->cap*sizeof(double));}e->checks[e->nchecks++]=c;}
void engine_register_all(Engine*e){int n;Check*cs;cs=mem_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=sec_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=syntax_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=type_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=perf_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=concurrency_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=quality_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=buf_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=c_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=cpp_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=csharp_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=java_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=js_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=ts_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=python_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=ruby_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=php_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=go_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=rust_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=swift_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=kotlin_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=scala_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=dart_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=haskell_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=lua_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=r_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=julia_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=perl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=shell_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=sql_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=html_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=css_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=yaml_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=objectivec_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=groovy_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=fortran_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=cobol_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=basic_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=pascal_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=ada_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=lisp_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=prolog_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=erlang_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=elixir_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=clojure_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=fsharp_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=visualbasic_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=powershell_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=matlab_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=d_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=dockerfile_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=json_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=toml_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=cmake_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=makefile_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=tex_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=vue_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=svelte_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=solidity_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=graphql_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=tcl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=coffeescript_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=nim_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=zig_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=ocaml_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=purescript_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=racket_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=scheme_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=verilog_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=vhdl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=vala_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=thrift_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=smalltalk_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=apl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=awk_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=forth_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=idl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=opencl_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=openscad_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=protobuf_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=sas_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=stata_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);cs=viml_checks_get(&n);for(int i=0;i<n;i++)engine_register_check(e,cs[i]);}
void engine_set_verbose(Engine*e,int v){e->verbose=v;}
void engine_run_check(Engine*e,Check*ck,SourceFile*f,Project*p,int idx){if(!e||!ck||!f||!p)return;Issue iss;memset(&iss,0,sizeof(iss));double start_time=clock();int cnt=ck->func(f,p,&iss);double end_time=clock();if(cnt>0){if(e->verbose){code_scan_printf("[CHECK] %s found %d issues in %s\n",ck->name,cnt,f->path);}e->total_issues+=cnt;e->check_counts[idx]+=cnt;if(f->nissues<MTHOS_MAX_ISSUES){snprintf(iss.loc.file,sizeof(iss.loc.file),"%s",f->path);f->issues[f->nissues++]=iss;}}e->check_times[idx]+=(end_time-start_time)/CLOCKS_PER_SEC;}
int engine_analyze_file(Engine*e,SourceFile*f,Project*p){if(!e||!f||!p)return 0;int found=0;for(int i=0;i<e->nchecks;i++){Check*ck=&e->checks[i];if(ck->lang&&ck->lang!=f->lang)continue;int prev=e->total_issues;engine_run_check(e,ck,f,p,i);if(e->total_issues>prev)found=1;}return found;}
typedef struct{Engine*e;SourceFile**files;int start;int end;Project*p;int*results;}ThreadData;
static void*analyze_thread(void*arg){ThreadData*td=(ThreadData*)arg;int total=0;for(int i=td->start;i<td->end;i++){if(td->files[i]){total+=engine_analyze_file(td->e,td->files[i],td->p);}}*(td->results)=total;return NULL;}
int engine_analyze_project(Engine*e,Project*p){if(!e||!p)return 0;p->analysis_time=clock();int total=0;if(e->threads>1&&p->nfiles>1){int nthreads=e->threads<p->nfiles?e->threads:p->nfiles;ThreadData*td=calloc(nthreads,sizeof(ThreadData));pthread_t*threads=calloc(nthreads,sizeof(pthread_t));int*results=calloc(nthreads,sizeof(int));int chunk=p->nfiles/nthreads;for(int i=0;i<nthreads;i++){td[i].e=e;td[i].files=p->files;td[i].start=i*chunk;td[i].end=(i==nthreads-1)?p->nfiles:(i+1)*chunk;td[i].p=p;td[i].results=&results[i];pthread_create(&threads[i],NULL,analyze_thread,&td[i]);}for(int i=0;i<nthreads;i++){pthread_join(threads[i],NULL);total+=results[i];}free(td);free(threads);free(results);}else{for(int i=0;i<p->nfiles;i++){if(p->files[i])total+=engine_analyze_file(e,p->files[i],p);}}p->analysis_time=(clock()-p->analysis_time)/CLOCKS_PER_SEC;e->total_issues=total;return total;}
void engine_print_stats(Engine*e){if(!e)return;code_scan_printf("Analysis Engine Statistics:\n");code_scan_printf("  Total checks: %d\n",e->nchecks);code_scan_printf("  Total issues found: %d\n",e->total_issues);code_scan_printf("  Check details:\n");for(int i=0;i<e->nchecks;i++){if(e->check_counts[i]>0){code_scan_printf("    %-40s %5d issues  %6.3fs\n",e->checks[i].name,e->check_counts[i],e->check_times[i]);}}}
void engine_free(Engine*e){if(!e)return;free(e->checks);free(e->check_counts);free(e->check_times);free(e);}
