/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "checks_verilog.h"
int check_verilog_1(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LBRACE){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116001;snprintf(out->msg,sizeof(out->msg),"Type naming may need PascalCase in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Use PascalCase for type names");}}}return cnt;}
int check_verilog_2(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LPAREN){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116002;snprintf(out->msg,sizeof(out->msg),"Function naming may not follow Verilog conventions");snprintf(out->suggestion,sizeof(out->suggestion),"Review Verilog naming conventions");}}}return cnt;}
int check_verilog_3(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i].text[0]>='A'&&f->tokens[i].text[0]<='Z'){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116003;snprintf(out->msg,sizeof(out->msg),"Uppercase identifier - possible constant in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Verify constant naming style");}}}return cnt;}
int check_verilog_4(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){long long last=0;for(long long i=0;f->content[i];i++){if(f->content[i]=='\n'){if(i-last>120){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116004;snprintf(out->msg,sizeof(out->msg),"Line exceeds 120 chars in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Break long lines");if(cnt>=1)break;}last=i+1;}}if(cnt==0&&f->size-last>120){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116004;snprintf(out->msg,sizeof(out->msg),"Line exceeds 120 chars in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Break long lines");}}}return cnt;}}
int check_verilog_5(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){for(long long i=0;f->content[i];i++){if(f->content[i]==' '&&(f->content[i+1]=='\n'||f->content[i+1]=='\r'||f->content[i+1]==0)){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116005;snprintf(out->msg,sizeof(out->msg),"Trailing whitespace in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Remove trailing whitespace");if(cnt>=1)break;}}}return cnt;}}
int check_verilog_6(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){int has_tabs=0,has_spaces=0;for(long long i=0;f->content[i]&&(!has_tabs||!has_spaces);i++){if(f->content[i]=='\t')has_tabs=1;if(f->content[i]==' '&&(i==0||f->content[i-1]=='\n'))has_spaces=1;}if(has_tabs&&has_spaces){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116006;snprintf(out->msg,sizeof(out->msg),"Mixed spaces and tabs in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Use consistent indentation");}}}return cnt;}
int check_verilog_7(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->size==0||(f->content&&f->content[0]==0)){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=116007;snprintf(out->msg,sizeof(out->msg),"Empty Verilog source file");snprintf(out->suggestion,sizeof(out->suggestion),"Add content or remove file");}}return cnt;}
int check_verilog_8(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_STRING&&f->tokens[i].text[0]){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116008;snprintf(out->msg,sizeof(out->msg),"String literal in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Consider externalizing strings");}}}return cnt;}
int check_verilog_9(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){char*buf=code_scan_strdup(f->content);if(buf){char*lower=code_scan_lower(buf);if(lower){if(strstr(lower,"todo")||strstr(lower,"fixme")||strstr(lower,"hack")||strstr(lower,"xxx")){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116009;snprintf(out->msg,sizeof(out->msg),"TODO/FIXME found in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Address before release");}}}free(buf);}return cnt;}}
int check_verilog_10(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_NUMBER&&f->tokens[i].val>100){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116010;snprintf(out->msg,sizeof(out->msg),"Magic number 116010 in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Use named constant");}}}return cnt;}
int check_verilog_11(SourceFile*f,Project*p,Issue*out){int cnt=0;int pc=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_LPAREN)pc++;if(f->tokens[i].type==TK_RPAREN)pc--;}if(pc!=0){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=116011;snprintf(out->msg,sizeof(out->msg),"Unbalanced parentheses in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Check parenthesis matching");}}return cnt;}
int check_verilog_12(SourceFile*f,Project*p,Issue*out){int cnt=0;int bc=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_LBRACE||f->tokens[i].type==TK_BLOCK_OPEN)bc++;if(f->tokens[i].type==TK_RBRACE||f->tokens[i].type==TK_BLOCK_CLOSE)bc--;}if(bc!=0){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=116012;snprintf(out->msg,sizeof(out->msg),"Unbalanced braces in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Check brace matching");}}return cnt;}
int check_verilog_13(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_SEMI&&f->tokens[i+1].type==TK_SEMI){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116013;snprintf(out->msg,sizeof(out->msg),"Double semicolon in Verilog");snprintf(out->suggestion,sizeof(out->suggestion),"Remove extra semicolon");}}}return cnt;}
int check_verilog_14(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_ID&&strlen(f->tokens[i].text)>40){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=116014;snprintf(out->msg,sizeof(out->msg),"Long identifier (%zu chars) in Verilog",strlen(f->tokens[i].text));snprintf(out->suggestion,sizeof(out->suggestion),"Shorten identifier name");}}}return cnt;}
int check_verilog_15(SourceFile*f,Project*p,Issue*out){int cnt=0;int maxd=0,cur=0;for(int i=0;i<f->ntokens;i++){int t=f->tokens[i].type;if(t==TK_BLOCK_OPEN||t==TK_LBRACE||t==TK_LPAREN||t==TK_LBRACK)cur++;if(t==TK_BLOCK_CLOSE||t==TK_RBRACE||t==TK_RPAREN||t==TK_RBRACK)cur--;if(cur>maxd)maxd=cur;}if(maxd>8){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=116015;snprintf(out->msg,sizeof(out->msg),"Deep nesting (depth %d) in Verilog",maxd);snprintf(out->suggestion,sizeof(out->suggestion),"Refactor to reduce nesting");}}return cnt;}
Check*verilog_checks_get(int*n){
static Check cs[15];
cs[0]=(Check){"check_verilog_1",check_verilog_1,CAT_LANG_SPECIFIC,116001,LANG_VERILOG};
cs[1]=(Check){"check_verilog_2",check_verilog_2,CAT_LANG_SPECIFIC,116002,LANG_VERILOG};
cs[2]=(Check){"check_verilog_3",check_verilog_3,CAT_LANG_SPECIFIC,116003,LANG_VERILOG};
cs[3]=(Check){"check_verilog_4",check_verilog_4,CAT_LANG_SPECIFIC,116004,LANG_VERILOG};
cs[4]=(Check){"check_verilog_5",check_verilog_5,CAT_LANG_SPECIFIC,116005,LANG_VERILOG};
cs[5]=(Check){"check_verilog_6",check_verilog_6,CAT_LANG_SPECIFIC,116006,LANG_VERILOG};
cs[6]=(Check){"check_verilog_7",check_verilog_7,CAT_LANG_SPECIFIC,116007,LANG_VERILOG};
cs[7]=(Check){"check_verilog_8",check_verilog_8,CAT_LANG_SPECIFIC,116008,LANG_VERILOG};
cs[8]=(Check){"check_verilog_9",check_verilog_9,CAT_LANG_SPECIFIC,116009,LANG_VERILOG};
cs[9]=(Check){"check_verilog_10",check_verilog_10,CAT_LANG_SPECIFIC,116010,LANG_VERILOG};
cs[10]=(Check){"check_verilog_11",check_verilog_11,CAT_LANG_SPECIFIC,116011,LANG_VERILOG};
cs[11]=(Check){"check_verilog_12",check_verilog_12,CAT_LANG_SPECIFIC,116012,LANG_VERILOG};
cs[12]=(Check){"check_verilog_13",check_verilog_13,CAT_LANG_SPECIFIC,116013,LANG_VERILOG};
cs[13]=(Check){"check_verilog_14",check_verilog_14,CAT_LANG_SPECIFIC,116014,LANG_VERILOG};
cs[14]=(Check){"check_verilog_15",check_verilog_15,CAT_LANG_SPECIFIC,116015,LANG_VERILOG};
*n=15;return cs;
}
