/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "checks_sas.h"
int check_sas_1(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LBRACE){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128001;snprintf(out->msg,sizeof(out->msg),"Type naming may need PascalCase in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Use PascalCase for type names");}}}return cnt;}
int check_sas_2(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LPAREN){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128002;snprintf(out->msg,sizeof(out->msg),"Function naming may not follow SAS conventions");snprintf(out->suggestion,sizeof(out->suggestion),"Review SAS naming conventions");}}}return cnt;}
int check_sas_3(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i].text[0]>='A'&&f->tokens[i].text[0]<='Z'){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128003;snprintf(out->msg,sizeof(out->msg),"Uppercase identifier - possible constant in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Verify constant naming style");}}}return cnt;}
int check_sas_4(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){long long last=0;for(long long i=0;f->content[i];i++){if(f->content[i]=='\n'){if(i-last>120){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128004;snprintf(out->msg,sizeof(out->msg),"Line exceeds 120 chars in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Break long lines");if(cnt>=1)break;}last=i+1;}}if(cnt==0&&f->size-last>120){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128004;snprintf(out->msg,sizeof(out->msg),"Line exceeds 120 chars in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Break long lines");}}}return cnt;}}
int check_sas_5(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){for(long long i=0;f->content[i];i++){if(f->content[i]==' '&&(f->content[i+1]=='\n'||f->content[i+1]=='\r'||f->content[i+1]==0)){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128005;snprintf(out->msg,sizeof(out->msg),"Trailing whitespace in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Remove trailing whitespace");if(cnt>=1)break;}}}return cnt;}}
int check_sas_6(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){int has_tabs=0,has_spaces=0;for(long long i=0;f->content[i]&&(!has_tabs||!has_spaces);i++){if(f->content[i]=='\t')has_tabs=1;if(f->content[i]==' '&&(i==0||f->content[i-1]=='\n'))has_spaces=1;}if(has_tabs&&has_spaces){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128006;snprintf(out->msg,sizeof(out->msg),"Mixed spaces and tabs in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Use consistent indentation");}}}return cnt;}
int check_sas_7(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->size==0||(f->content&&f->content[0]==0)){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=128007;snprintf(out->msg,sizeof(out->msg),"Empty SAS source file");snprintf(out->suggestion,sizeof(out->suggestion),"Add content or remove file");}}return cnt;}
int check_sas_8(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_STRING&&f->tokens[i].text[0]){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128008;snprintf(out->msg,sizeof(out->msg),"String literal in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Consider externalizing strings");}}}return cnt;}
int check_sas_9(SourceFile*f,Project*p,Issue*out){int cnt=0;if(f->content){char*buf=code_scan_strdup(f->content);if(buf){char*lower=code_scan_lower(buf);if(lower){if(strstr(lower,"todo")||strstr(lower,"fixme")||strstr(lower,"hack")||strstr(lower,"xxx")){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128009;snprintf(out->msg,sizeof(out->msg),"TODO/FIXME found in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Address before release");}}}free(buf);}return cnt;}}
int check_sas_10(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_NUMBER&&f->tokens[i].val>100){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128010;snprintf(out->msg,sizeof(out->msg),"Magic number 128010 in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Use named constant");}}}return cnt;}
int check_sas_11(SourceFile*f,Project*p,Issue*out){int cnt=0;int pc=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_LPAREN)pc++;if(f->tokens[i].type==TK_RPAREN)pc--;}if(pc!=0){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=128011;snprintf(out->msg,sizeof(out->msg),"Unbalanced parentheses in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Check parenthesis matching");}}return cnt;}
int check_sas_12(SourceFile*f,Project*p,Issue*out){int cnt=0;int bc=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_LBRACE||f->tokens[i].type==TK_BLOCK_OPEN)bc++;if(f->tokens[i].type==TK_RBRACE||f->tokens[i].type==TK_BLOCK_CLOSE)bc--;}if(bc!=0){cnt++;if(cnt==1&&out){out->sev=SEV_ERROR;out->cat=CAT_LANG_SPECIFIC;out->code=128012;snprintf(out->msg,sizeof(out->msg),"Unbalanced braces in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Check brace matching");}}return cnt;}
int check_sas_13(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_SEMI&&f->tokens[i+1].type==TK_SEMI){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128013;snprintf(out->msg,sizeof(out->msg),"Double semicolon in SAS");snprintf(out->suggestion,sizeof(out->suggestion),"Remove extra semicolon");}}}return cnt;}
int check_sas_14(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_ID&&strlen(f->tokens[i].text)>40){cnt++;if(cnt==1&&out){out->sev=SEV_INFO;out->cat=CAT_LANG_SPECIFIC;out->code=128014;snprintf(out->msg,sizeof(out->msg),"Long identifier (%zu chars) in SAS",strlen(f->tokens[i].text));snprintf(out->suggestion,sizeof(out->suggestion),"Shorten identifier name");}}}return cnt;}
int check_sas_15(SourceFile*f,Project*p,Issue*out){int cnt=0;int maxd=0,cur=0;for(int i=0;i<f->ntokens;i++){int t=f->tokens[i].type;if(t==TK_BLOCK_OPEN||t==TK_LBRACE||t==TK_LPAREN||t==TK_LBRACK)cur++;if(t==TK_BLOCK_CLOSE||t==TK_RBRACE||t==TK_RPAREN||t==TK_RBRACK)cur--;if(cur>maxd)maxd=cur;}if(maxd>8){cnt++;if(cnt==1&&out){out->sev=SEV_WARNING;out->cat=CAT_LANG_SPECIFIC;out->code=128015;snprintf(out->msg,sizeof(out->msg),"Deep nesting (depth %d) in SAS",maxd);snprintf(out->suggestion,sizeof(out->suggestion),"Refactor to reduce nesting");}}return cnt;}
Check*sas_checks_get(int*n){
static Check cs[15];
cs[0]=(Check){"check_sas_1",check_sas_1,CAT_LANG_SPECIFIC,128001,LANG_SAS};
cs[1]=(Check){"check_sas_2",check_sas_2,CAT_LANG_SPECIFIC,128002,LANG_SAS};
cs[2]=(Check){"check_sas_3",check_sas_3,CAT_LANG_SPECIFIC,128003,LANG_SAS};
cs[3]=(Check){"check_sas_4",check_sas_4,CAT_LANG_SPECIFIC,128004,LANG_SAS};
cs[4]=(Check){"check_sas_5",check_sas_5,CAT_LANG_SPECIFIC,128005,LANG_SAS};
cs[5]=(Check){"check_sas_6",check_sas_6,CAT_LANG_SPECIFIC,128006,LANG_SAS};
cs[6]=(Check){"check_sas_7",check_sas_7,CAT_LANG_SPECIFIC,128007,LANG_SAS};
cs[7]=(Check){"check_sas_8",check_sas_8,CAT_LANG_SPECIFIC,128008,LANG_SAS};
cs[8]=(Check){"check_sas_9",check_sas_9,CAT_LANG_SPECIFIC,128009,LANG_SAS};
cs[9]=(Check){"check_sas_10",check_sas_10,CAT_LANG_SPECIFIC,128010,LANG_SAS};
cs[10]=(Check){"check_sas_11",check_sas_11,CAT_LANG_SPECIFIC,128011,LANG_SAS};
cs[11]=(Check){"check_sas_12",check_sas_12,CAT_LANG_SPECIFIC,128012,LANG_SAS};
cs[12]=(Check){"check_sas_13",check_sas_13,CAT_LANG_SPECIFIC,128013,LANG_SAS};
cs[13]=(Check){"check_sas_14",check_sas_14,CAT_LANG_SPECIFIC,128014,LANG_SAS};
cs[14]=(Check){"check_sas_15",check_sas_15,CAT_LANG_SPECIFIC,128015,LANG_SAS};
*n=15;return cs;
}
