/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "checks_types.h"
int check_implicit_func_decl(SourceFile*f,Project*p,Issue*out){int cnt=0;typedef struct{char name[256];int declared;}FuncDecl;static FuncDecl*fdecls=NULL;static int nf=0,cf=0;if(fdecls==NULL){cf=256;fdecls=calloc(cf,sizeof(FuncDecl));}for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LPAREN){char*fname=f->tokens[i].text;int found=0;for(int j=0;j<nf;j++){if(strcmp(fdecls[j].name,fname)==0){found=1;fdecls[j].declared=1;break;}}if(!found){int is_type=lexer_is_type_keyword(fname);if(!is_type&&strcmp(fname,"printf")!=0&&strcmp(fname,"scanf")!=0&&strcmp(fname,"fopen")!=0&&strcmp(fname,"malloc")!=0&&strcmp(fname,"free")!=0&&strcmp(fname,"memcpy")!=0&&strcmp(fname,"strlen")!=0&&strcmp(fname,"strcmp")!=0&&strcmp(fname,"exit")!=0&&strcmp(fname,"atoi")!=0){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4001;snprintf(out->msg,sizeof(out->msg),"Implicit function declaration: '%s'",fname);snprintf(out->suggestion,sizeof(out->suggestion),"Include proper header or declare function prototype");}}}}}return cnt;}
int check_implicit_int(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-2;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_ID&&f->tokens[i+2].type==TK_LPAREN){int is_type=lexer_is_type_keyword(f->tokens[i].text);if(!is_type){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4002;snprintf(out->msg,sizeof(out->msg),"Implicit int type for '%s'",f->tokens[i].text);snprintf(out->suggestion,sizeof(out->suggestion),"Add explicit type specifier");}}}}return cnt;}
int check_type_mismatch(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-3;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_EQ){char*var=f->tokens[i].text;int var_type=0;for(int j=i-1;j>=0&&j>i-10;j--){int t=sym_get_type_id(f->tokens[j].text);if(t>0){var_type=t;break;}}if(var_type>0&&f->tokens[i+2].type==TK_NUMBER&&var_type==6){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4003;snprintf(out->msg,sizeof(out->msg),"Type mismatch in assignment to '%s'",var);}}}}return cnt;}
int check_ptr_mismatch(SourceFile*f,Project*p,Issue*out){int cnt=0;int i; for(i=0;i<f->ntokens-3;i++){if(f->tokens[i].type==TK_ID&&i>0&&f->tokens[i-1].type==TK_STAR&&f->tokens[i+1].type==TK_EQ){int j=i+2;if(j<f->ntokens&&f->tokens[j].type==TK_AMP&&f->tokens[j+1].type==TK_ID){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4004;snprintf(out->msg,sizeof(out->msg),"Pointer type mismatch: assigning address to pointer");}}}}if(f->tokens[i].type==TK_ID&&i>1&&f->tokens[i-1].type==TK_STAR&&f->tokens[i-2].type==TK_STAR&&f->tokens[i+1].type==TK_EQ){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4004;snprintf(out->msg,sizeof(out->msg),"Pointer type mismatch: assigning to pointer-to-pointer");}}return cnt;}
int check_assignment_type(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-2;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_EQ&&f->tokens[i+2].type==TK_STRING){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4005;snprintf(out->msg,sizeof(out->msg),"Assignment from string literal to non-const variable");snprintf(out->suggestion,sizeof(out->suggestion),"Use 'const char*' for string literals");}}}return cnt;}
int check_func_proto_mismatch(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-2;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LPAREN){char*fname=f->tokens[i].text;int nparams=0;int j=i+2;while(j<f->ntokens&&f->tokens[j].type!=TK_RPAREN){if(f->tokens[j].type==TK_ID||f->tokens[j].type==TK_INT||f->tokens[j].type==TK_CHAR||f->tokens[j].type==TK_VOID)nparams++;j++;}int call_params=0;j=i+2;while(j<f->ntokens&&f->tokens[j].type!=TK_RPAREN){if(f->tokens[j].type==TK_COMMA)call_params++;j++;}if(call_params>10&&nparams==0){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4006;snprintf(out->msg,sizeof(out->msg),"Possible function prototype mismatch for '%s'",fname);}}}}return cnt;}
int check_return_type(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-1;i++){if(f->tokens[i].type==TK_RETURN){int j=i+1;while(j<f->ntokens&&f->tokens[j].type==TK_SEMI)j++;if(j<f->ntokens&&f->tokens[j].type==TK_ID){char*val=f->tokens[j].text;for(int k=i-1;k>=0&&k>i-20;k--){if(f->tokens[k].type==TK_VOID){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_ERROR;out->cat=CAT_TYPE;out->code=4007;snprintf(out->msg,sizeof(out->msg),"Returning value from void function");}break;}}}}else{for(int k=i-1;k>=0&&k>i-20;k--){if(f->tokens[k].type==TK_INT||f->tokens[k].type==TK_CHAR||f->tokens[k].type==TK_FLOAT||f->tokens[k].type==TK_DOUBLE){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4007;snprintf(out->msg,sizeof(out->msg),"Non-void function missing return value");}break;}}}}return cnt;}
int check_arg_type(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-3;i++){int j=i+2;if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_LPAREN){int depth=1;while(j<f->ntokens&&depth>0){if(f->tokens[j].type==TK_LPAREN)depth++;if(f->tokens[j].type==TK_RPAREN)depth--;j++;}}if(j>i+2){for(int k=i+2;k<j-1;k++){if(f->tokens[k].type==TK_STRING&&strchr(f->tokens[k].text,'%')==NULL){TokenType pt=f->tokens[i-1].type;}}}}return cnt;}
int check_null_compare(SourceFile*f,Project*p,Issue*out){int cnt=0;int i; for(i=0;i<f->ntokens-2;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_EQ&&f->tokens[i+2].type==TK_ID&&strcmp(f->tokens[i+2].text,"NULL")==0){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4009;snprintf(out->msg,sizeof(out->msg),"Comparison with NULL using == instead of !");}}}if(f->tokens[i].type==TK_LPAREN&&f->tokens[i+1].type==TK_ID&&f->tokens[i+2].type==TK_RPAREN){cnt++;}return cnt;}
int check_enum_mismatch(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-2;i++){if(f->tokens[i].type==TK_ID&&f->tokens[i+1].type==TK_EQ&&f->tokens[i+2].type==TK_NUMBER){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_INFO;out->cat=CAT_TYPE;out->code=4010;snprintf(out->msg,sizeof(out->msg),"Direct integer assignment to variable");}}}return cnt;}
int check_struct_assignment(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_STRUCT){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_INFO;out->cat=CAT_TYPE;out->code=4011;snprintf(out->msg,sizeof(out->msg),"Struct usage detected - verify member access");}}}return cnt;}
int check_union_type(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens;i++){if(f->tokens[i].type==TK_UNION){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_INFO;out->cat=CAT_TYPE;out->code=4012;snprintf(out->msg,sizeof(out->msg),"Union type detected - type punning may cause undefined behavior");}}}return cnt;}
int check_void_pointer_arithmetic(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-3;i++){if(f->tokens[i].type==TK_LPAREN&&f->tokens[i+1].type==TK_VOID&&f->tokens[i+2].type==TK_STAR){int j=i+3;while(j<f->ntokens-2){if(f->tokens[j].type==TK_ID){if(f->tokens[j+1].type==TK_PLUS||f->tokens[j+1].type==TK_MINUS){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_ERROR;out->cat=CAT_TYPE;out->code=4013;snprintf(out->msg,sizeof(out->msg),"Arithmetic on void pointer is a GCC extension");}}break;}j++;}}}return cnt;}
int check_function_pointer_cast(SourceFile*f,Project*p,Issue*out){int cnt=0;for(int i=0;i<f->ntokens-5;i++){if(f->tokens[i].type==TK_LPAREN&&f->tokens[i+1].type==TK_LPAREN&&f->tokens[i+2].type==TK_STAR&&f->tokens[i+3].type==TK_ID&&f->tokens[i+4].type==TK_RPAREN){cnt++;if(cnt==1&&out){LOC_TOK(out,f,i);out->sev=SEV_WARNING;out->cat=CAT_TYPE;out->code=4014;snprintf(out->msg,sizeof(out->msg),"Function pointer cast detected - may cause UB");snprintf(out->suggestion,sizeof(out->suggestion),"Ensure function pointer signatures match exactly");}}}return cnt;}
Check*type_checks_get(int*n){static Check checks[]={
{"implicit_func_decl",check_implicit_func_decl,CAT_TYPE,4001,0},
{"implicit_int",check_implicit_int,CAT_TYPE,4002,0},
{"type_mismatch",check_type_mismatch,CAT_TYPE,4003,0},
{"ptr_mismatch",check_ptr_mismatch,CAT_TYPE,4004,0},
{"assignment_type",check_assignment_type,CAT_TYPE,4005,0},
{"func_proto_mismatch",check_func_proto_mismatch,CAT_TYPE,4006,0},
{"return_type",check_return_type,CAT_TYPE,4007,0},
{"arg_type",check_arg_type,CAT_TYPE,4008,0},
{"null_compare",check_null_compare,CAT_TYPE,4009,0},
{"enum_mismatch",check_enum_mismatch,CAT_TYPE,4010,0},
{"struct_assignment",check_struct_assignment,CAT_TYPE,4011,0},
{"union_type",check_union_type,CAT_TYPE,4012,0},
{"void_pointer_arithmetic",check_void_pointer_arithmetic,CAT_TYPE,4013,0},
{"func_pointer_cast",check_function_pointer_cast,CAT_TYPE,4014,0},
};*n=sizeof(checks)/sizeof(checks[0]);return checks;}
