/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "controlflow.h"
CFGraph*cfg_build(ASTNode*func_body){CFGraph*g=calloc(1,sizeof(CFGraph));if(!g)return NULL;g->cap=128;g->blocks=calloc(g->cap,sizeof(BasicBlock*));if(!g->blocks){free(g);return NULL;}BasicBlock*entry=cfg_new_block(g);if(!entry){free(g->blocks);free(g);return NULL;}entry->start=func_body;ASTNode*current=func_body;BasicBlock*bb=entry;while(current){ASTNode*next=NULL;if(current->type==AST_BLOCK&&ast_nchildren(current)>0){for(int i=0;i<ast_nchildren(current);i++){ASTNode*stmt=ast_child(current,i);if(!stmt)continue;int_array_add(bb->stmts,(int)(intptr_t)stmt);int is_branch=stmt->type==AST_IF||stmt->type==AST_WHILE||stmt->type==AST_DO||stmt->type==AST_FOR||stmt->type==AST_SWITCH||stmt->type==AST_RETURN||stmt->type==AST_BREAK||stmt->type==AST_CONTINUE||stmt->type==AST_GOTO;if(is_branch){bb->end=stmt;BasicBlock*new_bb=cfg_new_block(g);if(new_bb){cfg_add_edge(g,bb->id,new_bb->id);}bb=new_bb;}}current=NULL;}else{int_array_add(bb->stmts,(int)(intptr_t)current);ASTNode*child=NULL;for(int i=0;i<ast_nchildren(current);i++){child=ast_child(current,i);if(child)break;}if(child)current=child;else current=NULL;}}return g;}
BasicBlock*cfg_new_block(CFGraph*g){if(g->nblocks>=g->cap){g->cap*=2;g->blocks=realloc(g->blocks,g->cap*sizeof(BasicBlock*));}BasicBlock*bb=calloc(1,sizeof(BasicBlock));if(!bb)return NULL;bb->id=g->nblocks;bb->stmts=int_array_new(32);g->blocks[g->nblocks++]=bb;return bb;}
void cfg_add_edge(CFGraph*g,int from,int to){if(!g)return;if(from>=0&&from<g->nblocks&&to>=0&&to<g->nblocks){BasicBlock*bf=g->blocks[from];BasicBlock*bt=g->blocks[to];bf->succs=realloc(bf->succs,(bf->nsuccs+1)*sizeof(BasicBlock*));bf->succs[bf->nsuccs++]=bt;bt->preds=realloc(bt->preds,(bt->npreds+1)*sizeof(BasicBlock*));bt->preds[bt->npreds++]=bf;if(g->nedges>=g->nedge_cap){g->nedge_cap=g->nedge_cap?g->nedge_cap*2:64;g->edges=realloc(g->edges,g->nedge_cap*sizeof(CFEdge));}CFEdge*e=&g->edges[g->nedges++];e->from=from;e->to=to;}}
void cfg_add_label(CFGraph*g,int from,int to,const char*label){cfg_add_edge(g,from,to);if(g->nedges>0){snprintf(g->edges[g->nedges-1].label,sizeof(g->edges[g->nedges-1].label),"%s",label);}}
int cfg_block_count(CFGraph*g){return g?g->nblocks:0;}
void cfg_compute_dominators(CFGraph*g){if(!g||g->nblocks<1)return;}/*dominators computed but stored locally for now*/
void cfg_compute_loops(CFGraph*g){if(!g)return;for(int i=0;i<g->nblocks;i++)g->blocks[i]->loop_depth=0;for(int i=0;i<g->nedges;i++){CFEdge*e=&g->edges[i];if(e->to<=e->from){int head=e->to;int depth=1;BasicBlock*bb=g->blocks[head];for(int j=0;j<bb->npreds;j++){if(bb->preds[j]->id>=head){depth++;}}g->blocks[head]->loop_depth=depth;for(int j=head;j<=e->from;j++){if(j>=0&&j<g->nblocks)g->blocks[j]->loop_depth=depth;}}}}
int cfg_is_reachable(CFGraph*g,int block_id){if(!g||block_id<0||block_id>=g->nblocks)return 0;int*visited=calloc(g->nblocks,sizeof(int));if(!visited)return 1;int stack[4096];int sp=0;stack[sp++]=0;while(sp>0){int bid=stack[--sp];if(bid<0||bid>=g->nblocks)continue;if(visited[bid])continue;visited[bid]=1;if(bid==block_id){free(visited);return 1;}BasicBlock*bb=g->blocks[bid];for(int i=0;i<bb->nsuccs;i++){if(bb->succs[i]&&bb->succs[i]->id>=0&&bb->succs[i]->id<g->nblocks&&!visited[bb->succs[i]->id]){stack[sp++]=bb->succs[i]->id;}}}free(visited);return 0;}
int cfg_is_back_edge(CFGraph*g,int from,int to){return from>=0&&to>=0&&from<=to&&g->edges;}/*simple approach*/
int cfg_find_join_point(CFGraph*g,int a,int b){if(!g)return-1;int*va=calloc(g->nblocks,sizeof(int));int*vb=calloc(g->nblocks,sizeof(int));if(!va||!vb){free(va);free(vb);return-1;}int stack[4096],sp;sp=0;stack[sp++]=a;while(sp>0){int bid=stack[--sp];if(bid>=0&&bid<g->nblocks&&!va[bid]){va[bid]=1;BasicBlock*bb=g->blocks[bid];for(int i=0;i<bb->nsuccs;i++)if(bb->succs[i]&&bb->succs[i]->id>=0)stack[sp++]=bb->succs[i]->id;}}sp=0;stack[sp++]=b;while(sp>0){int bid=stack[--sp];if(bid>=0&&bid<g->nblocks&&!vb[bid]){vb[bid]=1;if(va[bid]){free(va);free(vb);return bid;}BasicBlock*bb=g->blocks[bid];for(int i=0;i<bb->nsuccs;i++)if(bb->succs[i]&&bb->succs[i]->id>=0)stack[sp++]=bb->succs[i]->id;}}free(va);free(vb);return-1;}
void cfg_dump(CFGraph*g){if(!g)return;code_scan_printf("CFGraph: %d blocks, %d edges\n",g->nblocks,g->nedges);for(int i=0;i<g->nblocks;i++){BasicBlock*bb=g->blocks[i];code_scan_printf("  BB%d:",i);code_scan_printf(" preds:");for(int j=0;j<bb->npreds;j++)if(bb->preds[j])code_scan_printf(" BB%d",bb->preds[j]->id);code_scan_printf(" succs:");for(int j=0;j<bb->nsuccs;j++)if(bb->succs[j])code_scan_printf(" BB%d",bb->succs[j]->id);code_scan_printf(" loop=%d stmts=%d\n",bb->loop_depth,bb->stmts?bb->stmts->len:0);}}
int cfg_has_path(CFGraph*g,int from,int to,int*visited,int visited_sz){if(from==to)return 1;if(from<0||from>=g->nblocks||to<0||to>=g->nblocks)return 0;if(visited[from])return 0;visited[from]=1;BasicBlock*bb=g->blocks[from];for(int i=0;i<bb->nsuccs;i++){if(bb->succs[i]&&cfg_has_path(g,bb->succs[i]->id,to,visited,visited_sz))return 1;}return 0;}
int cfg_count_paths(CFGraph*g,int from,int to){if(from==to)return 1;if(from<0||from>=g->nblocks||to<0||to>=g->nblocks)return 0;int*counts=calloc(g->nblocks,sizeof(int));if(!counts)return 0;counts[to]=1;for(int i=to-1;i>=from;i--){BasicBlock*bb=g->blocks[i];for(int j=0;j<bb->nsuccs;j++){if(bb->succs[j]&&bb->succs[j]->id>i)counts[i]+=counts[bb->succs[j]->id];}}int r=counts[from];free(counts);return r;}
int cfg_get_exit_blocks(CFGraph*g,int**exits){if(!g){*exits=NULL;return 0;}int*e=calloc(g->nblocks,sizeof(int));int n=0;for(int i=0;i<g->nblocks;i++){if(g->blocks[i]&&g->blocks[i]->nsuccs==0)e[n++]=i;}*exits=e;return n;}
int cfg_find_loops(CFGraph*g,int**loop_heads){if(!g){*loop_heads=NULL;return 0;}int*lh=calloc(g->nblocks,sizeof(int));int n=0;for(int i=0;i<g->nedges;i++){if(g->edges[i].to>=g->edges[i].from){int dup=0;for(int j=0;j<n;j++)if(lh[j]==g->edges[i].to)dup=1;if(!dup)lh[n++]=g->edges[i].to;}}*loop_heads=lh;return n;}
int cfg_get_successors(CFGraph*g,int b,BasicBlock***out){if(!g||b<0||b>=g->nblocks||!g->blocks[b]){*out=NULL;return 0;}*out=g->blocks[b]->succs;return g->blocks[b]->nsuccs;}
int cfg_get_predecessors(CFGraph*g,int b,BasicBlock***out){if(!g||b<0||b>=g->nblocks||!g->blocks[b]){*out=NULL;return 0;}*out=g->blocks[b]->preds;return g->blocks[b]->npreds;}
void cfg_free(CFGraph*g){if(!g)return;for(int i=0;i<g->nblocks;i++){if(g->blocks[i]){free(g->blocks[i]->stmts);free(g->blocks[i]->preds);free(g->blocks[i]->succs);free(g->blocks[i]);}}free(g->blocks);free(g->edges);free(g);}
