/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "lexer.h"
static const char*kw[]={"auto","break","case","char","const","continue","default","do","double","else","enum","extern","float","for","goto","if","inline","int","long","register","restrict","return","short","signed","sizeof","static","struct","switch","typedef","union","unsigned","void","volatile","while","_Bool","_Complex","__attribute__","__asm__","__asm",0};
static const int kw_t[]={TK_AUTO,TK_BREAK,TK_CASE,TK_CHAR,TK_CONST,TK_CONTINUE,TK_DEFAULT,TK_DO,TK_DOUBLE,TK_ELSE,TK_ENUM,TK_EXTERN,TK_FLOAT,TK_FOR,TK_GOTO,TK_IF,TK_INLINE,TK_INT,TK_LONG,TK_REGISTER,TK_RESTRICT,TK_RETURN,TK_SHORT,TK_SIGNED,TK_UNSIGNED,TK_SIZEOF,TK_STATIC,TK_STRUCT,TK_SWITCH,TK_TYPEDEF,TK_UNION,TK_UNSIGNED,TK_VOID,TK_VOLATILE,TK_WHILE,TK_BOOL,TK_COMPLEX,TK_ATTRIBUTE,TK_ASM,TK_ASM,0};
void lexer_init(LexerState*ls,const char*content,const char*file){memset(ls,0,sizeof(*ls));ls->start=(char*)content;ls->cur=(char*)content;ls->end=(char*)content+strlen(content);code_scan_snprintf(ls->file,sizeof(ls->file),"%s",file);ls->line=1;ls->col=1;ls->prev_tok.type=TK_UNKNOWN;}
int lexer_get_pos(LexerState*ls,int*line,int*col){*line=ls->line;*col=ls->col;return 1;}
void lexer_skip_whitespace(LexerState*ls){while(ls->cur<ls->end){char c=*ls->cur;if(c==' '||c=='\t'||c=='\v'||c=='\f'){ls->cur++;ls->col++;}else if(c=='\n'){ls->cur++;ls->line++;ls->col=1;}else if(c=='\r'){ls->cur++;ls->col=1;if(ls->cur<ls->end&&*ls->cur=='\n'){ls->cur++;ls->line++;}}else break;}}
void lexer_skip_comment(LexerState*ls){if(ls->cur>=ls->end)return;if(*ls->cur=='/'&&(ls->cur+1)<ls->end){if(*(ls->cur+1)=='/'){ls->cur+=2;ls->col+=2;while(ls->cur<ls->end&&*ls->cur!='\n'){ls->cur++;ls->col++;}return;}if(*(ls->cur+1)=='*'){ls->cur+=2;ls->col+=2;while(ls->cur<ls->end){if(*ls->cur=='*'&&(ls->cur+1)<ls->end&&*(ls->cur+1)=='/'){ls->cur+=2;ls->col+=2;return;}if(*ls->cur=='\n'){ls->line++;ls->col=1;}else{ls->col++;}ls->cur++;}ls->error=1;return;}}}
int lexer_is_keyword(const char*s){for(int i=0;kw[i];i++){if(strcmp(s,kw[i])==0)return 1;}return 0;}
int lexer_is_type_keyword(const char*s){return strcmp(s,"int")==0||strcmp(s,"char")==0||strcmp(s,"short")==0||strcmp(s,"long")==0||strcmp(s,"float")==0||strcmp(s,"double")==0||strcmp(s,"void")==0||strcmp(s,"signed")==0||strcmp(s,"unsigned")==0||strcmp(s,"_Bool")==0||strcmp(s,"_Complex")==0||strcmp(s,"struct")==0||strcmp(s,"union")==0||strcmp(s,"enum")==0;}
Token lexer_read_number(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.type=TK_NUMBER;t.line=ls->line;t.col=ls->col;char*start=ls->cur;int is_float=0;if(ls->cur<ls->end&&*ls->cur=='0'){ls->cur++;ls->col++;if(ls->cur<ls->end&&(*ls->cur=='x'||*ls->cur=='X')){ls->cur++;ls->col++;while(ls->cur<ls->end&&util_is_hex_digit(*ls->cur)){ls->cur++;ls->col++;}}else if(ls->cur<ls->end&&*ls->cur=='b'||*ls->cur=='B'){ls->cur++;ls->col++;while(ls->cur<ls->end&&(*ls->cur=='0'||*ls->cur=='1')){ls->cur++;ls->col++;}}else{while(ls->cur<ls->end&&util_is_octal_digit(*ls->cur)){ls->cur++;ls->col++;}}}else{while(ls->cur<ls->end&&util_is_digit(*ls->cur)){ls->cur++;ls->col++;}}if(ls->cur<ls->end&&*ls->cur=='.'){is_float=1;ls->cur++;ls->col++;while(ls->cur<ls->end&&util_is_digit(*ls->cur)){ls->cur++;ls->col++;}}if(ls->cur<ls->end&&(*ls->cur=='e'||*ls->cur=='E')){is_float=1;ls->cur++;ls->col++;if(ls->cur<ls->end&&(*ls->cur=='+'||*ls->cur=='-')){ls->cur++;ls->col++;}while(ls->cur<ls->end&&util_is_digit(*ls->cur)){ls->cur++;ls->col++;}}if(ls->cur<ls->end&&(*ls->cur=='f'||*ls->cur=='F'||*ls->cur=='l'||*ls->cur=='L')){is_float=1;ls->cur++;ls->col++;}size_t len=(size_t)(ls->cur-start);if(len>=sizeof(t.text))len=sizeof(t.text)-1;memcpy(t.text,start,len);t.text[len]=0;if(is_float)t.fval=strtod(t.text,NULL);else t.val=strtoll(t.text,NULL,0);return t;}
Token lexer_read_string(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.type=TK_STRING;t.line=ls->line;t.col=ls->col;char quote=*ls->cur;ls->cur++;ls->col++;char*buf=malloc(MTHOS_MAX_LINE);int bi=0;while(ls->cur<ls->end&&*ls->cur!=quote){if(*ls->cur=='\\'){ls->cur++;ls->col++;if(ls->cur>=ls->end)break;char c=*ls->cur;switch(c){case'n':buf[bi++]='\n';break;case't':buf[bi++]='\t';break;case'r':buf[bi++]='\r';break;case'0':buf[bi++]='\0';break;case'\\':buf[bi++]='\\';break;case'\"':buf[bi++]='\"';break;case'\'':buf[bi++]='\'';break;case'x':{ls->cur++;ls->col++;int v=0;for(int i=0;i<2&&ls->cur<ls->end&&util_is_hex_digit(*ls->cur);i++){v=(v<<4)+util_hex_to_int(*ls->cur);ls->cur++;ls->col++;}buf[bi++]=(char)v;continue;}default:{if(c>='0'&&c<='7'){int v=0;for(int i=0;i<3&&ls->cur<ls->end&&util_is_octal_digit(*ls->cur);i++){v=(v<<3)+(*ls->cur-'0');ls->cur++;ls->col++;}buf[bi++]=(char)v;continue;}buf[bi++]=c;break;}}}else{buf[bi++]=*ls->cur;ls->cur++;ls->col++;}if(bi>=MTHOS_MAX_LINE-1)break;}if(ls->cur<ls->end&&*ls->cur==quote){ls->cur++;ls->col++;}else{ls->error=1;}buf[bi]=0;code_scan_snprintf(t.text,sizeof(t.text),"%s",buf);free(buf);return t;}
Token lexer_read_char(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.type=TK_CHAR;t.line=ls->line;t.col=ls->col;ls->cur++;ls->col++;if(ls->cur<ls->end&&*ls->cur=='\\'){ls->cur++;ls->col++;if(ls->cur<ls->end){t.val=*ls->cur;switch(*ls->cur){case'n':t.val='\n';break;case't':t.val='\t';break;case'r':t.val='\r';break;case'0':t.val='\0';break;case'\\':t.val='\\';break;case'\'':t.val='\'';break;case'\"':t.val='\"';break;}ls->cur++;ls->col++;}}else{if(ls->cur<ls->end){t.val=*ls->cur;ls->cur++;ls->col++;}}if(ls->cur<ls->end&&*ls->cur=='\''){ls->cur++;ls->col++;}else{ls->error=1;}code_scan_snprintf(t.text,sizeof(t.text),"%c",(char)t.val);return t;}
Token lexer_read_ident(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.line=ls->line;t.col=ls->col;char*start=ls->cur;while(ls->cur<ls->end&&(util_is_ident_char(*ls->cur))){ls->cur++;ls->col++;}size_t len=(size_t)(ls->cur-start);if(len>=sizeof(t.text))len=sizeof(t.text)-1;memcpy(t.text,start,len);t.text[len]=0;if(lexer_is_keyword(t.text)){for(int i=0;kw[i];i++){if(strcmp(t.text,kw[i])==0){t.type=kw_t[i];break;}}}else t.type=TK_ID;return t;}
Token lexer_read_punct(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.line=ls->line;t.col=ls->col;t.type=TK_UNKNOWN;char c=*ls->cur;struct{const char*seq;TokenType type;}puncts[]={{"...",TK_ELLIPSIS},{">>=",TK_RSHIFT_EQ},{"<<=",TK_LSHIFT_EQ},{">>",TK_RSHIFT},{"<<",TK_LSHIFT},{"<=",TK_LE},{">=",TK_GE},{"==",TK_EQ},{"!=",TK_NEQ},{"+=",TK_PLUS_EQ},{"-=",TK_MINUS_EQ},{"*=",TK_STAR_EQ},{"/=",TK_SLASH_EQ},{"%=",TK_PERCENT_EQ},{"&=",TK_AMP_EQ},{"|=",TK_PIPE_EQ},{"^=",TK_CARET_EQ},{"++",TK_INC},{"--",TK_DEC},{"&&",TK_AND},{"||",TK_OR},{"->",TK_ARROW},{"##",TK_DBL_HASH},{";",TK_SEMI},{",",TK_COMMA},{"{",TK_BLOCK_OPEN},{"}",TK_BLOCK_CLOSE},{"(",TK_LPAREN},{")",TK_RPAREN},{"[",TK_LBRACK},{"]",TK_RBRACK},{".",TK_DOT},{"+",TK_PLUS},{"-",TK_MINUS},{"*",TK_STAR},{"/",TK_SLASH},{"%",TK_PERCENT},{"&",TK_AMP},{"|",TK_PIPE},{"^",TK_CARET},{"~",TK_TILDE},{"!",TK_EXCL},{"?",TK_QUESTION},{":",TK_COLON},{"=",TK_EQ},{"<",TK_LT},{">",TK_GT},{"#",TK_HASH},{0,TK_UNKNOWN}};for(int i=0;puncts[i].seq;i++){size_t sl=strlen(puncts[i].seq);if((size_t)(ls->end-ls->cur)>=sl&&memcmp(ls->cur,puncts[i].seq,sl)==0){t.type=puncts[i].type;code_scan_snprintf(t.text,sizeof(t.text),"%s",puncts[i].seq);ls->cur+=sl;ls->col+=(int)sl;return t;}}t.text[0]=c;t.text[1]=0;ls->cur++;ls->col++;return t;}
Token lexer_next(LexerState*ls){Token t;memset(&t,0,sizeof(t));t.type=TK_EOF;t.line=ls->line;t.col=ls->col;ls->prev_tok=t;while(ls->cur<ls->end){lexer_skip_whitespace(ls);if(ls->cur>=ls->end)break;if(*ls->cur=='/'&&(ls->cur+1)<ls->end&&(*(ls->cur+1)=='/'||*(ls->cur+1)=='*')){lexer_skip_comment(ls);continue;}char c=*ls->cur;if(util_is_ident_char(c)&&!util_is_digit(c)){Token id=lexer_read_ident(ls);if(id.type==TK_ASM||id.type==TK_ATTRIBUTE)return id;lexer_skip_whitespace(ls);if(id.type==TK_ID&&ls->cur<ls->end&&*ls->cur=='(')return id;return id;}if(util_is_digit(c))return lexer_read_number(ls);if(c=='\"')return lexer_read_string(ls);if(c=='\'')return lexer_read_char(ls);if(c=='#'){Token pp;memset(&pp,0,sizeof(pp));pp.type=TK_HASH;pp.line=ls->line;pp.col=ls->col;pp.text[0]='#';pp.text[1]=0;ls->cur++;ls->col++;return pp;}return lexer_read_punct(ls);}t.type=TK_EOF;code_scan_snprintf(t.text,sizeof(t.text),"EOF");return t;}
Token lexer_peek(LexerState*ls){LexerState save=*ls;Token t=lexer_next(ls);*ls=save;return t;}
Token lexer_prev(LexerState*ls){return ls->prev_tok;}
int lexer_tokenize(LexerState*ls,Token*tokens,int max_tokens){int n=0;while(n<max_tokens){Token t=lexer_next(ls);tokens[n++]=t;if(t.type==TK_EOF)break;}tokens[n-1].type=TK_EOF;return n;}
char*lexer_type_str(TokenType t){static char buf[32];switch(t){case TK_EOF:return "EOF";case TK_ID:return "IDENTIFIER";case TK_NUMBER:return "NUMBER";case TK_STRING:return "STRING";case TK_CHAR:return "CHAR";case TK_LBRACE:return "LBRACE";case TK_RBRACE:return "RBRACE";case TK_LPAREN:return "LPAREN";case TK_RPAREN:return "RPAREN";case TK_LBRACK:return "LBRACK";case TK_RBRACK:return "RBRACK";case TK_SEMI:return "SEMICOLON";case TK_COMMA:return "COMMA";case TK_DOT:return "DOT";case TK_ARROW:return "ARROW";case TK_PLUS:return "PLUS";case TK_MINUS:return "MINUS";case TK_STAR:return "STAR";case TK_SLASH:return "SLASH";case TK_PERCENT:return "PERCENT";case TK_AMP:return "AMP";case TK_PIPE:return "PIPE";case TK_CARET:return "CARET";case TK_TILDE:return "TILDE";case TK_EXCL:return "EXCL";case TK_QUESTION:return "QUESTION";case TK_COLON:return "COLON";case TK_EQ:return "EQ";case TK_NEQ:return "NEQ";case TK_LT:return "LT";case TK_GT:return "GT";case TK_LE:return "LE";case TK_GE:return "GE";case TK_LSHIFT:return "LSHIFT";case TK_RSHIFT:return "RSHIFT";case TK_INC:return "INC";case TK_DEC:return "DEC";case TK_AND:return "AND";case TK_OR:return "OR";case TK_ELLIPSIS:return "ELLIPSIS";case TK_IF:return "IF";case TK_ELSE:return "ELSE";case TK_SWITCH:return "SWITCH";case TK_CASE:return "CASE";case TK_DEFAULT:return "DEFAULT";case TK_WHILE:return "WHILE";case TK_DO:return "DO";case TK_FOR:return "FOR";case TK_RETURN:return "RETURN";case TK_BREAK:return "BREAK";case TK_CONTINUE:return "CONTINUE";case TK_GOTO:return "GOTO";case TK_TYPEDEF:return "TYPEDEF";case TK_EXTERN:return "EXTERN";case TK_STATIC:return "STATIC";case TK_CONST:return "CONST";case TK_VOLATILE:return "VOLATILE";case TK_RESTRICT:return "RESTRICT";case TK_VOID:return "VOID";case TK_SHORT:return "SHORT";case TK_INT:return "INT";case TK_LONG:return "LONG";case TK_FLOAT:return "FLOAT";case TK_DOUBLE:return "DOUBLE";case TK_SIGNED:return "SIGNED";case TK_UNSIGNED:return "UNSIGNED";case TK_BOOL:return "BOOL";case TK_STRUCT:return "STRUCT";case TK_UNION:return "UNION";case TK_ENUM:return "ENUM";case TK_SIZEOF:return "SIZEOF";case TK_ATTRIBUTE:return "ATTRIBUTE";case TK_ASM:return "ASM";case TK_BLOCK_OPEN:return "{";case TK_BLOCK_CLOSE:return "}";case TK_HASH:return "HASH";case TK_UNKNOWN:return "UNKNOWN";default:sprintf(buf,"TOKEN_%d",t);return buf;}}
