/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "parser.h"
void parser_init(ParserState*ps,Token*tokens,int len,SourceFile*file){memset(ps,0,sizeof(*ps));ps->tokens=tokens;ps->len=len;ps->pos=0;ps->file=file;ps->depth=0;}
int parser_match(ParserState*ps,TokenType t){if(ps->pos<ps->len&&ps->tokens[ps->pos].type==t){ps->pos++;return 1;}return 0;}
int parser_peek_is(ParserState*ps,TokenType t){return ps->pos<ps->len&&ps->tokens[ps->pos].type==t;}
Token parser_advance(ParserState*ps){if(ps->pos<ps->len)return ps->tokens[ps->pos++];Token t;memset(&t,0,sizeof(t));t.type=TK_EOF;return t;}
Token parser_peek(ParserState*ps,int ahead){int idx=ps->pos+ahead;if(idx>=0&&idx<ps->len)return ps->tokens[idx];Token t;memset(&t,0,sizeof(t));t.type=TK_EOF;return t;}
void parser_error(ParserState*ps,const char*msg){ps->error_count++;Issue iss;memset(&iss,0,sizeof(iss));if(ps->pos<ps->len&&ps->pos>=0){iss.loc.line=ps->tokens[ps->pos].line;iss.loc.col=ps->tokens[ps->pos].col;}if(ps->file)snprintf(iss.loc.file,sizeof(iss.loc.file),"%s",ps->file->path);iss.sev=SEV_ERROR;iss.cat=CAT_SYNTAX;iss.code=1000;snprintf(iss.msg,sizeof(iss.msg),"Parser: %s",msg);if(ps->file)ps->file->issues[ps->file->nissues++]=iss;}
ASTNode*ast_new(int type,Token*tok){ASTNode*n=calloc(1,sizeof(ASTNode));if(!n)return NULL;n->type=type;if(tok){n->loc.line=tok->line;n->loc.col=tok->col;if(tok->text[0])snprintf(n->name,sizeof(n->name),"%s",tok->text);n->tok=tok;}return n;}
ASTNode*ast_new_expr(void){ASTNode*n=calloc(1,sizeof(ASTNode));n->type=AST_EXPR_STMT;return n;}
void ast_free_deep(ASTNode*n){if(!n)return;for(int i=0;i<n->nchildren;i++)ast_free_deep(n->children[i]);if(n->str_val)free(n->str_val);free(n->children);free(n);}
ASTNode*parser_expr(ParserState*ps);ASTNode*parser_declaration(ParserState*ps);ASTNode*parser_statement(ParserState*ps);ASTNode*parser_block(ParserState*ps);
ASTNode*parser_translation_unit(ParserState*ps){ASTNode*unit=ast_new(AST_FILE,NULL);while(ps->pos<ps->len&&ps->tokens[ps->pos].type!=TK_EOF){ASTNode*decl=parser_declaration(ps);if(decl)ast_add_child(unit,decl);else{if(ps->pos<ps->len&&ps->tokens[ps->pos].type!=TK_EOF)parser_advance(ps);else break;}}return unit;}
ASTNode*parser_parse(ParserState*ps){return parser_translation_unit(ps);}
static int parser_is_type_start(TokenType t){return t==TK_VOID||t==TK_CHAR||t==TK_SHORT||t==TK_INT||t==TK_LONG||t==TK_FLOAT||t==TK_DOUBLE||t==TK_SIGNED||t==TK_UNSIGNED||t==TK_BOOL||t==TK_COMPLEX||t==TK_CONST||t==TK_VOLATILE||t==TK_EXTERN||t==TK_STATIC||t==TK_INLINE||t==TK_TYPEDEF||t==TK_STRUCT||t==TK_UNION||t==TK_ENUM||t==TK_ID;}
ASTNode*parser_struct_or_union(ParserState*ps){int is_union=parser_match(ps,TK_UNION);if(!is_union)parser_match(ps,TK_STRUCT);ASTNode*s=ast_new(is_union?AST_UNION:AST_STRUCT,NULL);if(parser_peek_is(ps,TK_ID)){Token name=parser_advance(ps);snprintf(s->name,sizeof(s->name),"%s",name.text);}if(parser_peek_is(ps,TK_BLOCK_OPEN)||parser_peek_is(ps,TK_LBRACE)){parser_advance(ps);while(!parser_peek_is(ps,TK_BLOCK_CLOSE)&&!parser_peek_is(ps,TK_RBRACE)&&ps->pos<ps->len){if(parser_peek_is(ps,TK_STRUCT)||parser_peek_is(ps,TK_UNION)){ASTNode*inner=parser_struct_or_union(ps);if(inner)ast_add_child(s,inner);parser_match(ps,TK_SEMI);continue;}while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE))parser_advance(ps);TokenType mts[]={TK_CHAR,TK_SHORT,TK_INT,TK_LONG,TK_FLOAT,TK_DOUBLE,TK_VOID,TK_SIGNED,TK_UNSIGNED,TK_BOOL,TK_ID};int mf=0;for(size_t i=0;i<sizeof(mts)/sizeof(mts[0]);i++){if(parser_peek_is(ps,mts[i])){mf=1;break;}}if(!mf)break;while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE))parser_advance(ps);for(size_t i=0;i<sizeof(mts)/sizeof(mts[0]);i++)parser_match(ps,mts[i]);while(parser_match(ps,TK_STAR));if(parser_peek_is(ps,TK_ID)){Token mn=parser_advance(ps);ASTNode*mem=ast_new(AST_MEMBER,&mn);ast_add_child(s,mem);while(parser_match(ps,TK_COMMA)){if(parser_peek_is(ps,TK_ID)){Token mn2=parser_advance(ps);ASTNode*mem2=ast_new(AST_MEMBER,&mn2);ast_add_child(s,mem2);}}}if(parser_peek_is(ps,TK_COLON)){parser_advance(ps);if(parser_peek_is(ps,TK_NUMBER))parser_advance(ps);}parser_match(ps,TK_SEMI);}if(parser_peek_is(ps,TK_BLOCK_CLOSE)||parser_peek_is(ps,TK_RBRACE))parser_advance(ps);}if(parser_peek_is(ps,TK_ID)){Token tn=parser_advance(ps);ast_add_child(s,ast_new(AST_IDENT,&tn));}parser_match(ps,TK_SEMI);return s;}
ASTNode*parser_enum(ParserState*ps){parser_match(ps,TK_ENUM);ASTNode*e=ast_new(AST_ENUM,NULL);if(parser_peek_is(ps,TK_ID)){Token n=parser_advance(ps);snprintf(e->name,sizeof(e->name),"%s",n.text);}if(parser_peek_is(ps,TK_BLOCK_OPEN)||parser_peek_is(ps,TK_LBRACE)){parser_advance(ps);int ev=0;while(!parser_peek_is(ps,TK_BLOCK_CLOSE)&&!parser_peek_is(ps,TK_RBRACE)&&ps->pos<ps->len){if(parser_peek_is(ps,TK_ID)){Token en=parser_advance(ps);ASTNode*evn=ast_new(AST_ENUM_VAL,&en);evn->ival=ev;if(parser_match(ps,TK_EQ)){if(parser_peek_is(ps,TK_NUMBER)){Token nv=parser_advance(ps);ev=(int)nv.val;evn->ival=ev;}}ast_add_child(e,evn);ev++;}if(parser_peek_is(ps,TK_COMMA))parser_advance(ps);else break;}if(parser_peek_is(ps,TK_BLOCK_CLOSE)||parser_peek_is(ps,TK_RBRACE))parser_advance(ps);}parser_match(ps,TK_SEMI);return e;}
ASTNode*parser_typedef(ParserState*ps){parser_match(ps,TK_TYPEDEF);ASTNode*t=ast_new(AST_TYPEDEF,NULL);while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE))parser_advance(ps);TokenType tts[]={TK_CHAR,TK_SHORT,TK_INT,TK_LONG,TK_FLOAT,TK_DOUBLE,TK_VOID,TK_SIGNED,TK_UNSIGNED,TK_BOOL,TK_STRUCT,TK_UNION,TK_ENUM,TK_ID};for(size_t i=0;i<sizeof(tts)/sizeof(tts[0]);i++){if(parser_peek_is(ps,tts[i])){Token tt=parser_advance(ps);ast_add_child(t,ast_new(AST_TYPE_NAME,&tt));}}while(parser_match(ps,TK_STAR))ast_add_child(t,ast_new(AST_POINTER,NULL));if(parser_peek_is(ps,TK_ID)){Token tn=parser_advance(ps);snprintf(t->name,sizeof(t->name),"%s",tn.text);}parser_match(ps,TK_SEMI);return t;}
ASTNode*parser_type_name(ParserState*ps){ASTNode*t=ast_new(AST_TYPE_NAME,NULL);while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE)||parser_peek_is(ps,TK_EXTERN)||parser_peek_is(ps,TK_STATIC))parser_advance(ps);TokenType tts[]={TK_VOID,TK_CHAR,TK_SHORT,TK_INT,TK_LONG,TK_FLOAT,TK_DOUBLE,TK_SIGNED,TK_UNSIGNED,TK_BOOL,TK_COMPLEX,TK_STRUCT,TK_UNION,TK_ENUM,TK_ID};for(size_t i=0;i<sizeof(tts)/sizeof(tts[0]);i++){if(parser_peek_is(ps,tts[i])){Token tt=parser_advance(ps);ast_add_child(t,ast_new(AST_TYPE_NAME,&tt));}}while(parser_match(ps,TK_STAR))ast_add_child(t,ast_new(AST_POINTER,NULL));return t;}
ASTNode*parser_parameter(ParserState*ps){ASTNode*p=ast_new(AST_PARAM,NULL);while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE)||parser_peek_is(ps,TK_RESTRICT))parser_advance(ps);TokenType ts[]={TK_VOID,TK_CHAR,TK_SHORT,TK_INT,TK_LONG,TK_FLOAT,TK_DOUBLE,TK_SIGNED,TK_UNSIGNED,TK_BOOL,TK_COMPLEX,TK_STRUCT,TK_UNION,TK_ENUM,TK_ID};int found=0;for(size_t i=0;i<sizeof(ts)/sizeof(ts[0]);i++){if(parser_peek_is(ps,ts[i])){found=1;break;}}if(!found){if(parser_peek_is(ps,TK_RPAREN)||parser_peek_is(ps,TK_COMMA)||parser_peek_is(ps,TK_ELLIPSIS)){if(parser_match(ps,TK_ELLIPSIS))snprintf(p->name,sizeof(p->name),"...");return p;}return NULL;}while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE)||parser_peek_is(ps,TK_RESTRICT))parser_advance(ps);for(size_t i=0;i<sizeof(ts)/sizeof(ts[0]);i++){if(parser_match(ps,ts[i]))continue;}while(parser_match(ps,TK_STAR));if(parser_peek_is(ps,TK_ID)){Token n=parser_advance(ps);snprintf(p->name,sizeof(p->name),"%s",n.text);}return p;}
ASTNode*parser_parameter_list(ParserState*ps){ASTNode*pl=ast_new(AST_PARAM,NULL);if(parser_match(ps,TK_VOID)&&parser_peek_is(ps,TK_RPAREN))return pl;ps->pos--;while(!parser_peek_is(ps,TK_RPAREN)&&ps->pos<ps->len){ASTNode*p=parser_parameter(ps);if(p)ast_add_child(pl,p);if(parser_peek_is(ps,TK_COMMA))parser_advance(ps);else break;}return pl;}
ASTNode*parser_function_def(ParserState*ps,Token*name){ASTNode*fd=ast_new(AST_FUNC_DEF,name);snprintf(fd->name,sizeof(fd->name),"%s",name->text);parser_match(ps,TK_LPAREN);while(!parser_peek_is(ps,TK_RPAREN)&&ps->pos<ps->len){ASTNode*param=parser_parameter(ps);if(param)ast_add_child(fd,param);if(parser_peek_is(ps,TK_COMMA))parser_advance(ps);else break;}parser_match(ps,TK_RPAREN);parser_match(ps,TK_SEMI);if(parser_peek_is(ps,TK_BLOCK_OPEN)||parser_peek_is(ps,TK_LBRACE)){ASTNode*body=parser_block(ps);if(body)ast_add_child(fd,body);}return fd;}
ASTNode*parser_declaration(ParserState*ps){if(ps->depth>10000){parser_error(ps,"max depth");ps->depth--;return NULL;}ps->depth++;Token tk=parser_peek(ps,0);if(tk.type==TK_EOF){ps->depth--;return NULL;}if(tk.type==TK_TYPEDEF){ps->depth--;return parser_typedef(ps);}if(tk.type==TK_STRUCT||tk.type==TK_UNION){ps->depth--;return parser_struct_or_union(ps);}if(tk.type==TK_ENUM){ps->depth--;return parser_enum(ps);}if(tk.type==TK_SEMI){parser_advance(ps);ps->depth--;return NULL;}if(!parser_is_type_start(tk.type)){if(tk.type==TK_ID&&parser_peek(ps,1).type==TK_LPAREN){Token name=parser_advance(ps);ASTNode*fd=parser_function_def(ps,&name);ps->depth--;return fd;}ps->depth--;return NULL;}
while(parser_peek_is(ps,TK_CONST)||parser_peek_is(ps,TK_VOLATILE)||parser_peek_is(ps,TK_EXTERN)||parser_peek_is(ps,TK_STATIC)||parser_peek_is(ps,TK_INLINE)||parser_peek_is(ps,TK_TYPEDEF))parser_advance(ps);
TokenType spec[]={TK_CHAR,TK_SHORT,TK_INT,TK_LONG,TK_FLOAT,TK_DOUBLE,TK_VOID,TK_SIGNED,TK_UNSIGNED,TK_BOOL,TK_COMPLEX,TK_STRUCT,TK_UNION,TK_ENUM,TK_ID};int spec_found=0;for(size_t i=0;i<sizeof(spec)/sizeof(spec[0]);i++){if(parser_peek_is(ps,spec[i])){spec_found=1;break;}}if(!spec_found){ps->depth--;return NULL;}
while(1){int sf=0;for(size_t i=0;i<sizeof(spec)/sizeof(spec[0]);i++){if(parser_peek_is(ps,spec[i])){parser_advance(ps);sf=1;break;}}if(!sf)break;}
while(parser_match(ps,TK_STAR));Token name_tk=parser_peek(ps,0);if(name_tk.type==TK_ID&&parser_peek(ps,1).type==TK_LPAREN){parser_advance(ps);ASTNode*fd=parser_function_def(ps,&name_tk);ps->depth--;return fd;}
if(name_tk.type==TK_ID){parser_advance(ps);if(parser_peek_is(ps,TK_LPAREN)){ASTNode*fd=parser_function_def(ps,&name_tk);ps->depth--;return fd;}ASTNode*var=ast_new(AST_VAR_DECL,&name_tk);if(parser_peek_is(ps,TK_EQ)){parser_advance(ps);ASTNode*init=parser_assignment(ps);if(init)ast_add_child(var,init);}while(parser_match(ps,TK_COMMA)){Token cn=parser_advance(ps);ASTNode*other=ast_new(AST_VAR_DECL,&cn);ast_add_child(var,other);}parser_match(ps,TK_SEMI);ps->depth--;return var;}
parser_match(ps,TK_SEMI);ps->depth--;return NULL;}
ASTNode*parser_block(ParserState*ps){ASTNode*block=ast_new(AST_BLOCK,NULL);if(parser_match(ps,TK_LBRACE)||parser_match(ps,TK_BLOCK_OPEN)){while(!parser_peek_is(ps,TK_RBRACE)&&!parser_peek_is(ps,TK_BLOCK_CLOSE)&&ps->pos<ps->len&&!parser_peek_is(ps,TK_EOF)){if(parser_peek_is(ps,TK_SEMI)){parser_advance(ps);continue;}ASTNode*stmt=parser_statement(ps);if(stmt)ast_add_child(block,stmt);else{if(parser_peek_is(ps,TK_RBRACE)||parser_peek_is(ps,TK_BLOCK_CLOSE))break;parser_advance(ps);}}if(parser_peek_is(ps,TK_RBRACE)||parser_peek_is(ps,TK_BLOCK_CLOSE))parser_advance(ps);}return block;}
ASTNode*parser_if(ParserState*ps){parser_match(ps,TK_IF);parser_match(ps,TK_LPAREN);ASTNode*cond=parser_expr(ps);parser_match(ps,TK_RPAREN);ASTNode*then=parser_statement(ps);ASTNode*els=NULL;if(parser_peek_is(ps,TK_ELSE)){parser_advance(ps);els=parser_statement(ps);}ASTNode*in=ast_new(AST_IF,NULL);if(cond)ast_add_child(in,cond);if(then)ast_add_child(in,then);if(els)ast_add_child(in,els);return in;}
ASTNode*parser_while(ParserState*ps){parser_match(ps,TK_WHILE);parser_match(ps,TK_LPAREN);ASTNode*cond=parser_expr(ps);parser_match(ps,TK_RPAREN);ASTNode*body=parser_statement(ps);ASTNode*w=ast_new(AST_WHILE,NULL);if(cond)ast_add_child(w,cond);if(body)ast_add_child(w,body);return w;}
ASTNode*parser_do(ParserState*ps){parser_match(ps,TK_DO);ASTNode*body=parser_statement(ps);parser_match(ps,TK_WHILE);parser_match(ps,TK_LPAREN);ASTNode*cond=parser_expr(ps);parser_match(ps,TK_RPAREN);parser_match(ps,TK_SEMI);ASTNode*d=ast_new(AST_DO,NULL);if(body)ast_add_child(d,body);if(cond)ast_add_child(d,cond);return d;}
ASTNode*parser_for(ParserState*ps){parser_match(ps,TK_FOR);parser_match(ps,TK_LPAREN);ASTNode*init=NULL;ASTNode*cond=NULL;ASTNode*inc=NULL;if(!parser_peek_is(ps,TK_SEMI)){init=parser_expr(ps);}parser_match(ps,TK_SEMI);if(!parser_peek_is(ps,TK_SEMI)){cond=parser_expr(ps);}parser_match(ps,TK_SEMI);if(!parser_peek_is(ps,TK_RPAREN)){inc=parser_expr(ps);}parser_match(ps,TK_RPAREN);ASTNode*body=parser_statement(ps);ASTNode*f=ast_new(AST_FOR,NULL);if(init)ast_add_child(f,init);if(cond)ast_add_child(f,cond);if(inc)ast_add_child(f,inc);if(body)ast_add_child(f,body);return f;}
ASTNode*parser_switch(ParserState*ps){parser_match(ps,TK_SWITCH);parser_match(ps,TK_LPAREN);ASTNode*expr=parser_expr(ps);parser_match(ps,TK_RPAREN);ASTNode*body=parser_statement(ps);ASTNode*s=ast_new(AST_SWITCH,NULL);if(expr)ast_add_child(s,expr);if(body)ast_add_child(s,body);return s;}
ASTNode*parser_case(ParserState*ps){if(parser_peek_is(ps,TK_DEFAULT)){parser_advance(ps);ASTNode*d=ast_new(AST_DEFAULT,NULL);parser_match(ps,TK_COLON);ASTNode*stmt=parser_statement(ps);if(stmt)ast_add_child(d,stmt);return d;}parser_match(ps,TK_CASE);ASTNode*c=ast_new(AST_CASE,NULL);if(parser_peek_is(ps,TK_NUMBER)){Token v=parser_advance(ps);c->num_val=v.val;}else{ASTNode*e=parser_expr(ps);if(e)ast_add_child(c,e);}parser_match(ps,TK_COLON);ASTNode*stmt=parser_statement(ps);if(stmt)ast_add_child(c,stmt);return c;}
ASTNode*parser_return(ParserState*ps){parser_match(ps,TK_RETURN);ASTNode*r=ast_new(AST_RETURN,NULL);if(!parser_peek_is(ps,TK_SEMI)){ASTNode*e=parser_expr(ps);if(e)ast_add_child(r,e);}parser_match(ps,TK_SEMI);return r;}
ASTNode*parser_statement(ParserState*ps){if(ps->depth>10000){parser_error(ps,"max depth");ps->depth--;return NULL;}ps->depth++;Token tk=parser_peek(ps,0);ASTNode*stmt=NULL;switch(tk.type){case TK_IF:stmt=parser_if(ps);break;case TK_WHILE:stmt=parser_while(ps);break;case TK_DO:stmt=parser_do(ps);break;case TK_FOR:stmt=parser_for(ps);break;case TK_SWITCH:stmt=parser_switch(ps);break;case TK_CASE:case TK_DEFAULT:stmt=parser_case(ps);break;case TK_RETURN:stmt=parser_return(ps);break;case TK_BREAK:{parser_advance(ps);stmt=ast_new(AST_BREAK,NULL);parser_match(ps,TK_SEMI);break;}case TK_CONTINUE:{parser_advance(ps);stmt=ast_new(AST_CONTINUE,NULL);parser_match(ps,TK_SEMI);break;}case TK_GOTO:{parser_advance(ps);stmt=ast_new(AST_GOTO,NULL);if(parser_peek_is(ps,TK_ID)){Token l=parser_advance(ps);snprintf(stmt->name,sizeof(stmt->name),"%s",l.text);}parser_match(ps,TK_SEMI);break;}case TK_BLOCK_OPEN:case TK_LBRACE:stmt=parser_block(ps);break;case TK_SEMI:parser_advance(ps);stmt=ast_new(AST_EMPTY_STMT,NULL);break;default:{Token p2=parser_peek(ps,1);if(tk.type==TK_ID&&p2.type==TK_COLON){parser_advance(ps);parser_advance(ps);stmt=ast_new(AST_LABEL,NULL);snprintf(stmt->name,sizeof(stmt->name),"%s",tk.text);ASTNode*label_stmt=parser_statement(ps);if(label_stmt)ast_add_child(stmt,label_stmt);}else if(tk.type==TK_ID&&p2.type==TK_LPAREN){Token name=parser_advance(ps);stmt=parser_function_def(ps,&name);}else{ASTNode*expr=parser_expr(ps);if(expr){stmt=ast_new(AST_EXPR_STMT,NULL);ast_add_child(stmt,expr);parser_match(ps,TK_SEMI);}}}}ps->depth--;return stmt;}
ASTNode*parser_expr(ParserState*ps){ASTNode*e=parser_assignment(ps);if(parser_peek_is(ps,TK_COMMA)){ASTNode*comma=ast_new(AST_EXPR_STMT,NULL);ast_add_child(comma,e);while(parser_match(ps,TK_COMMA)){ASTNode*r=parser_assignment(ps);if(r)ast_add_child(comma,r);}return comma;}return e;}
ASTNode*parser_assignment(ParserState*ps){ASTNode*e=parser_conditional(ps);TokenType at[]={TK_EQ,TK_PLUS_EQ,TK_MINUS_EQ,TK_STAR_EQ,TK_SLASH_EQ,TK_PERCENT_EQ,TK_AMP_EQ,TK_PIPE_EQ,TK_CARET_EQ,TK_LSHIFT_EQ,TK_RSHIFT_EQ};for(size_t i=0;i<sizeof(at)/sizeof(at[0]);i++){if(parser_peek_is(ps,at[i])){Token op=parser_advance(ps);ASTNode*rhs=parser_assignment(ps);ASTNode*a=ast_new(AST_ASSIGN,NULL);ast_add_child(a,e);ast_add_child(a,rhs);a->op=op.type;e=a;break;}}return e;}
ASTNode*parser_conditional(ParserState*ps){ASTNode*e=parser_logical_or(ps);if(parser_peek_is(ps,TK_QUESTION)){parser_advance(ps);ASTNode*t=parser_expr(ps);parser_match(ps,TK_COLON);ASTNode*f=parser_conditional(ps);ASTNode*c=ast_new(AST_COND,NULL);ast_add_child(c,e);if(t)ast_add_child(c,t);if(f)ast_add_child(c,f);return c;}return e;}
ASTNode*parser_logical_or(ParserState*ps){ASTNode*e=parser_logical_and(ps);while(parser_peek_is(ps,TK_OR)){Token op=parser_advance(ps);ASTNode*r=parser_logical_and(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_logical_and(ParserState*ps){ASTNode*e=parser_bitwise_or(ps);while(parser_peek_is(ps,TK_AND)){Token op=parser_advance(ps);ASTNode*r=parser_bitwise_or(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_bitwise_or(ParserState*ps){ASTNode*e=parser_bitwise_xor(ps);while(parser_peek_is(ps,TK_PIPE)){Token op=parser_advance(ps);ASTNode*r=parser_bitwise_xor(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_bitwise_xor(ParserState*ps){ASTNode*e=parser_bitwise_and(ps);while(parser_peek_is(ps,TK_CARET)){Token op=parser_advance(ps);ASTNode*r=parser_bitwise_and(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_bitwise_and(ParserState*ps){ASTNode*e=parser_equality(ps);while(parser_peek_is(ps,TK_AMP)){Token op=parser_advance(ps);ASTNode*r=parser_equality(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_equality(ParserState*ps){ASTNode*e=parser_relational(ps);while(parser_peek_is(ps,TK_EQ)||parser_peek_is(ps,TK_NEQ)){Token op=parser_advance(ps);ASTNode*r=parser_relational(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_relational(ParserState*ps){ASTNode*e=parser_shift(ps);while(parser_peek_is(ps,TK_LT)||parser_peek_is(ps,TK_GT)||parser_peek_is(ps,TK_LE)||parser_peek_is(ps,TK_GE)){Token op=parser_advance(ps);ASTNode*r=parser_shift(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_shift(ParserState*ps){ASTNode*e=parser_additive(ps);while(parser_peek_is(ps,TK_LSHIFT)||parser_peek_is(ps,TK_RSHIFT)){Token op=parser_advance(ps);ASTNode*r=parser_additive(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_additive(ParserState*ps){ASTNode*e=parser_multiplicative(ps);while(parser_peek_is(ps,TK_PLUS)||parser_peek_is(ps,TK_MINUS)){Token op=parser_advance(ps);ASTNode*r=parser_multiplicative(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_multiplicative(ParserState*ps){ASTNode*e=parser_unary(ps);while(parser_peek_is(ps,TK_STAR)||parser_peek_is(ps,TK_SLASH)||parser_peek_is(ps,TK_PERCENT)){Token op=parser_advance(ps);ASTNode*r=parser_unary(ps);ASTNode*b=ast_new(AST_BINARY,NULL);ast_add_child(b,e);ast_add_child(b,r);b->op=op.type;e=b;}return e;}
ASTNode*parser_unary(ParserState*ps){if(parser_peek_is(ps,TK_INC)||parser_peek_is(ps,TK_DEC)){Token op=parser_advance(ps);ASTNode*o=parser_unary(ps);ASTNode*u=ast_new(AST_UNARY,NULL);ast_add_child(u,o);u->op=op.type;return u;}
int is_unary=parser_peek_is(ps,TK_AMP)||parser_peek_is(ps,TK_STAR)||parser_peek_is(ps,TK_PLUS)||parser_peek_is(ps,TK_MINUS)||parser_peek_is(ps,TK_TILDE)||parser_peek_is(ps,TK_EXCL);if(is_unary){Token op=parser_advance(ps);ASTNode*o=parser_unary(ps);ASTNode*u=ast_new(AST_UNARY,NULL);ast_add_child(u,o);u->op=op.type;return u;}
if(parser_peek_is(ps,TK_SIZEOF)){parser_advance(ps);ASTNode*s=ast_new(AST_SIZEOF,NULL);if(parser_peek_is(ps,TK_LPAREN)){parser_advance(ps);ASTNode*e=parser_type_name(ps);parser_match(ps,TK_RPAREN);if(e)ast_add_child(s,e);}else{ASTNode*e=parser_unary(ps);if(e)ast_add_child(s,e);}return s;}
if(parser_peek_is(ps,TK_LPAREN)){int save=ps->pos;parser_advance(ps);ASTNode*tname=parser_type_name(ps);if(tname&&parser_peek_is(ps,TK_RPAREN)){Token rp=parser_peek(ps,1);if(rp.type==TK_LPAREN||rp.type==TK_ID||rp.type==TK_NUMBER||rp.type==TK_STRING||rp.type==TK_AMP||rp.type==TK_STAR||rp.type==TK_INC||rp.type==TK_DEC||rp.type==TK_MINUS||rp.type==TK_EXCL||rp.type==TK_TILDE||rp.type==TK_SIZEOF){parser_advance(ps);ASTNode*e=parser_unary(ps);ASTNode*c=ast_new(AST_CAST,NULL);ast_add_child(c,tname);ast_add_child(c,e);return c;}}ps->pos=save;}
return parser_postfix(ps);}
ASTNode*parser_postfix(ParserState*ps){ASTNode*e=parser_primary(ps);while(1){if(parser_peek_is(ps,TK_LBRACK)){parser_advance(ps);ASTNode*idx=parser_expr(ps);parser_match(ps,TK_RBRACK);ASTNode*ie=ast_new(AST_INDEX,NULL);ast_add_child(ie,e);if(idx)ast_add_child(ie,idx);e=ie;}else if(parser_peek_is(ps,TK_LPAREN)){parser_advance(ps);ASTNode*call=ast_new(AST_CALL,NULL);ast_add_child(call,e);while(!parser_peek_is(ps,TK_RPAREN)&&ps->pos<ps->len){ASTNode*a=parser_assignment(ps);if(a)ast_add_child(call,a);if(parser_peek_is(ps,TK_COMMA))parser_advance(ps);else break;}parser_match(ps,TK_RPAREN);e=call;}else if(parser_peek_is(ps,TK_DOT)||parser_peek_is(ps,TK_ARROW)){int is_arrow=parser_peek_is(ps,TK_ARROW);parser_advance(ps);if(parser_peek_is(ps,TK_ID)){Token mn=parser_advance(ps);ASTNode*me=ast_new(is_arrow?AST_PTR_MEMBER:AST_MEMBER,NULL);ast_add_child(me,e);snprintf(me->name,sizeof(me->name),"%s",mn.text);e=me;}}else if(parser_peek_is(ps,TK_INC)||parser_peek_is(ps,TK_DEC)){Token op=parser_advance(ps);ASTNode*pe=ast_new(AST_UNARY,NULL);ast_add_child(pe,e);pe->op=op.type;e=pe;}else break;}return e;}
ASTNode*parser_primary(ParserState*ps){Token tk=parser_peek(ps,0);if(tk.type==TK_NUMBER){parser_advance(ps);return ast_new(AST_NUMBER,&tk);}
if(tk.type==TK_STRING){ASTNode*str=ast_new(AST_STRING,NULL);str->str_val=code_scan_strdup(tk.text);parser_advance(ps);while(parser_peek_is(ps,TK_STRING)){Token s=parser_advance(ps);char*old=str->str_val;str->str_val=code_scan_concat(old,s.text);free(old);}return str;}
if(tk.type==TK_CHAR){parser_advance(ps);return ast_new(AST_NUMBER,&tk);}
if(tk.type==TK_ID){parser_advance(ps);return ast_new(AST_IDENT,&tk);}
if(tk.type==TK_LPAREN){parser_advance(ps);ASTNode*e=parser_expr(ps);parser_match(ps,TK_RPAREN);return e;}
if(tk.type==TK_SEMI){parser_advance(ps);return ast_new(AST_EMPTY_STMT,NULL);}
return NULL;}
