/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "preprocessor.h"
void pp_init(Preprocessor*pp){memset(pp,0,sizeof(*pp));pp->cap=256;pp->macros=calloc(pp->cap,sizeof(MacroDef));pp->include_cap=64;pp->include_paths=calloc(pp->include_cap,sizeof(char*));pp_add_builtin(pp,"__CODE_SCAN__","1");pp_add_builtin(pp,"__STDC__","1");pp_add_builtin(pp,"__STDC_VERSION__","201112L");pp_add_builtin(pp,"__LINE__","0");pp_add_builtin(pp,"__FILE__","\"\"");}
void pp_add_include_path(Preprocessor*pp,const char*path){if(!path)return;if(pp->npaths>=pp->include_cap){pp->include_cap*=2;pp->include_paths=realloc(pp->include_paths,pp->include_cap*sizeof(char*));}pp->include_paths[pp->npaths++]=code_scan_strdup(path);}
void pp_add_builtin(Preprocessor*pp,const char*name,const char*value){pp_define(pp,name,value);}
void pp_define(Preprocessor*pp,const char*name,const char*value){for(int i=0;i<pp->nmacros;i++){if(strcmp(pp->macros[i].name,name)==0){if(value)snprintf(pp->macros[i].value,sizeof(pp->macros[i].value),"%s",value);pp->macros[i].is_defined=1;return;}}if(pp->nmacros>=pp->cap){pp->cap*=2;pp->macros=realloc(pp->macros,pp->cap*sizeof(MacroDef));}MacroDef*m=&pp->macros[pp->nmacros++];memset(m,0,sizeof(*m));snprintf(m->name,sizeof(m->name),"%s",name);if(value)snprintf(m->value,sizeof(m->value),"%s",value);else m->value[0]=0;m->is_defined=1;}
MacroDef*pp_find(Preprocessor*pp,const char*name){if(!pp||!name)return NULL;for(int i=0;i<pp->nmacros;i++){if(pp->macros[i].is_defined&&strcmp(pp->macros[i].name,name)==0)return &pp->macros[i];}return NULL;}
int pp_undef(Preprocessor*pp,const char*name){MacroDef*m=pp_find(pp,name);if(m){m->is_defined=0;return 1;}return 0;}
int pp_is_include_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#include",8)==0;}
int pp_is_define_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#define",7)==0;}
int pp_is_if_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#if",3)==0&&(p[3]==' '||p[3]=='\t');}
int pp_is_ifdef_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#ifdef",6)==0;}
int pp_is_endif_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strcmp(p,"#endif")==0;}
int pp_is_else_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strcmp(p,"#else")==0;}
int pp_is_elif_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#elif",5)==0;}
int pp_is_pragma_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#pragma",7)==0;}
int pp_is_error_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#error",6)==0;}
int pp_is_warning_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#warning",8)==0;}
int pp_is_line_line(const char*line){const char*p=line;while(*p==' '||*p=='\t')p++;return strncmp(p,"#line",5)==0;}
int pp_eval_condition(Preprocessor*pp,const char*expr){char*copy=code_scan_strdup(expr);if(!copy)return 1;char*p=copy;while(*p==' '||*p=='\t')p++;int defined=0;if(strncmp(p,"defined",7)==0){p+=7;while(*p==' '||*p=='\t')p++;if(*p=='(')p++;while(*p==' '||*p=='\t')p++;char name[256];int ni=0;while(*p&&*p!=')'&&*p!=' '&&*p!='\t'&&ni<255)name[ni++]=*p++;name[ni]=0;defined=pp_find(pp,name)!=0;free(copy);return defined;}if(strncmp(p,"!",1)==0){p++;while(*p==' '||*p=='\t')p++;if(strncmp(p,"defined",7)==0){p+=7;while(*p==' '||*p=='\t')p++;if(*p=='(')p++;while(*p==' '||*p=='\t')p++;char name[256];int ni=0;while(*p&&*p!=')'&&*p!=' '&&*p!='\t'&&ni<255)name[ni++]=*p++;name[ni]=0;defined=pp_find(pp,name)!=0;free(copy);return!defined;}}char *token=strtok(copy," \t");if(!token){free(copy);return 1;}long long result=0;int op=0;while(token){if(strcmp(token,"||")==0)op=1;else if(strcmp(token,"&&")==0)op=2;else if(strcmp(token,"==")==0)op=3;else if(strcmp(token,"!=")==0)op=4;else if(strcmp(token,"<")==0)op=5;else if(strcmp(token,">")==0)op=6;else if(strcmp(token,"<=")==0)op=7;else if(strcmp(token,">=")==0)op=8;else if(strcmp(token,"+")==0)op=9;else if(strcmp(token,"-")==0)op=10;else if(strcmp(token,"*")==0)op=11;else if(strcmp(token,"/")==0)op=12;else if(strcmp(token,"%")==0)op=13;else if(strcmp(token,"~")==0)op=14;else if(strcmp(token,"!")==0)op=15;else if(strcmp(token,"(")==0)op=16;else if(strcmp(token,")")==0)op=17;else{long long v=strtoll(token,NULL,0);if(op){switch(op){case1:result=result||v;break;case2:result=result&&v;break;case3:result=result==v;break;case4:result=result!=v;break;case5:result=result<v;break;case6:result=result>v;break;case7:result=result<=v;break;case8:result=result>=v;break;case9:result=result+v;break;case10:result=result-v;break;case11:result=result*v;break;case12:v?result=result/v:0;break;case13:v?result=result%v:0;break;case14:result=~v;break;case15:result=!v;break;default:result=v;}op=0;}else result=v;}token=strtok(NULL," \t");}free(copy);return result!=0;}
char*pp_preprocess(Preprocessor*pp,const char*source,const char*file,int*out_len){if(!source){if(out_len)*out_len=0;return NULL;}Buffer*buf=buffer_new((long long)strlen(source)*2);char*line_start=(char*)source;int in_skip=0;int skip_depth=0;while(*line_start){char*next=line_start;while(*next&&*next!='\n')next++;char saved=*next;*next=0;char*trimmed=line_start;while(*trimmed==' '||*trimmed=='\t')trimmed++;if(pp_is_if_line(trimmed)||pp_is_ifdef_line(trimmed)){const char*cond=trimmed+(pp_is_ifdef_line(trimmed)?6:3);while(*cond==' '||*cond=='\t')cond++;int result=pp_eval_condition(pp,cond);if(!result){if(!in_skip){in_skip=1;skip_depth=1;}else skip_depth++;}else if(in_skip){skip_depth++;}}else if(pp_is_endif_line(trimmed)){if(in_skip){if(skip_depth>0)skip_depth--;if(skip_depth==0)in_skip=0;}}else if(pp_is_else_line(trimmed)||pp_is_elif_line(trimmed)){if(in_skip&&skip_depth==1){in_skip=0;}else if(!in_skip){in_skip=1;skip_depth=1;}}else if(pp_is_define_line(trimmed)){char*eq=trimmed+7;while(*eq==' '||*eq=='\t')eq++;char*macro_name=eq;while(*eq&&*eq!=' '&&*eq!='\t'&&*eq!='(')eq++;char name_save=*eq;*eq=0;char*macro_val=eq+(name_save?1:0);if(name_save=='('){eq++;while(*eq&&*eq!=')')eq++;if(*eq==')'){eq++;macro_val=eq;}}while(*macro_val==' '||*macro_val=='\t')macro_val++;pp_define(pp,macro_name,macro_val);*eq=name_save;}else if(pp_is_include_line(trimmed)){char*inc=trimmed+8;while(*inc==' '||*inc=='\t')inc++;if(*inc=='\"'){inc++;char inc_path[CODE_SCAN_MAX_PATH];int pi=0;while(*inc&&*inc!='\"'&&pi<CODE_SCAN_MAX_PATH-1)inc_path[pi++]=*inc++;inc_path[pi]=0;if(!in_skip){buffer_printf(buf,"#include \"%s\"\n",inc_path);}}else if(*inc=='<'){inc++;char inc_path[CODE_SCAN_MAX_PATH];int pi=0;while(*inc&&*inc!='>'&&pi<CODE_SCAN_MAX_PATH-1)inc_path[pi++]=*inc++;inc_path[pi]=0;if(!in_skip){buffer_printf(buf,"#include <%s>\n",inc_path);}}}else if(!in_skip){buffer_append_str(buf,line_start);buffer_append_str(buf,"\n");}else if(pp_is_error_line(trimmed)){buffer_printf(buf,"#error %s\n",trimmed+6);}*next=saved;line_start=next;if(saved)line_start++;}int len=(int)buf->len;char*result=buffer_detach(buf);if(out_len)*out_len=len;return result;}
char*pp_expand_macros(Preprocessor*pp,const char*input,int*out_len){if(!input){if(out_len)*out_len=0;return NULL;}Buffer*buf=buffer_new((long long)strlen(input)*2);const char*p=input;while(*p){if((*p>='a'&&*p<='z')||(*p>='A'&&*p<='Z')||*p=='_'){char name[256];int ni=0;while((*p>='a'&&*p<='z')||(*p>='A'&&*p<='Z')||(*p>='0'&&*p<='9')||*p=='_'){if(ni<255)name[ni++]=*p;p++;}name[ni]=0;MacroDef*m=pp_find(pp,name);if(m&&m->value[0]){buffer_append_str(buf,m->value);}else{buffer_append(buf,name,(long long)ni);}}else{buffer_append(buf,p,1);p++;}}int len=(int)buf->len;char*result=buffer_detach(buf);if(out_len)*out_len=len;return result;}
void pp_free(Preprocessor*pp){if(pp->macros)free(pp->macros);for(int i=0;i<pp->npaths;i++)if(pp->include_paths[i])free(pp->include_paths[i]);if(pp->include_paths)free(pp->include_paths);memset(pp,0,sizeof(*pp));}
