/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "taint.h"
TaintGraph*taint_init(SourceFile*f){TaintGraph*tg=calloc(1,sizeof(TaintGraph));if(!tg)return NULL;tg->file=f;tg->cap=256;tg->vars=calloc(tg->cap,sizeof(TaintNode*));if(!tg->vars){free(tg);return NULL;}tg->flow=NULL;tg->nflow=0;tg->sink_count=0;tg->sinks=NULL;tg->nsink_cap=64;tg->sinks=malloc(tg->nsink_cap*sizeof(Location));return tg;}
int taint_add_var(TaintGraph*tg,const char*name,int source){if(!tg||!name)return-1;for(int i=0;i<tg->nvars;i++){if(tg->vars[i]&&strcmp(tg->vars[i]->name,name)==0)return i;}if(tg->nvars>=tg->cap){tg->cap*=2;tg->vars=realloc(tg->vars,tg->cap*sizeof(TaintNode*));}TaintNode*tn=calloc(1,sizeof(TaintNode));if(!tn)return-1;snprintf(tn->name,sizeof(tn->name),"%s",name);tn->var_id=tg->nvars;tn->source=source;tn->is_tainted=(source!=TS_NONE);tn->is_sanitized=0;tg->vars[tg->nvars]=tn;tg->nvars++;return tg->nvars-1;}
void taint_propagate(TaintGraph*tg,int from,int to){if(!tg||from<0||from>=tg->nvars||to<0||to>=tg->nvars)return;if(tg->vars[from]&&tg->vars[from]->is_tainted&&tg->vars[to]){tg->vars[to]->is_tainted=1;tg->vars[to]->source=tg->vars[from]->source;}int newcap=(tg->nflow+1)*2;tg->flow=realloc(tg->flow,newcap*sizeof(int*));tg->flow[tg->nflow]=malloc(2*sizeof(int));tg->flow[tg->nflow][0]=from;tg->flow[tg->nflow][1]=to;tg->nflow++;}
int taint_is_tainted(TaintGraph*tg,int var_id){if(!tg||var_id<0||var_id>=tg->nvars||!tg->vars[var_id])return 0;return tg->vars[var_id]->is_tainted;}
void taint_sanitize(TaintGraph*tg,int var_id){if(!tg||var_id<0||var_id>=tg->nvars||!tg->vars[var_id])return;tg->vars[var_id]->is_tainted=0;tg->vars[var_id]->is_sanitized=1;}
void taint_mark_sink(TaintGraph*tg,Location loc){if(!tg)return;if(tg->sink_count>=tg->nsink_cap){tg->nsink_cap*=2;tg->sinks=realloc(tg->sinks,tg->nsink_cap*sizeof(Location));}tg->sinks[tg->sink_count++]=loc;}
int taint_analyze(TaintGraph*tg){if(!tg)return 0;int changed=1;int max_iter=1000;int iter=0;while(changed&&iter<max_iter){changed=0;iter++;for(int i=0;i<tg->nflow;i++){int from=tg->flow[i][0];int to=tg->flow[i][1];if(from>=0&&from<tg->nvars&&to>=0&&to<tg->nvars&&tg->vars[from]&&tg->vars[to]){if(tg->vars[from]->is_tainted&&!tg->vars[to]->is_tainted){tg->vars[to]->is_tainted=1;tg->vars[to]->source=tg->vars[from]->source;changed=1;}}}}return tg->sink_count;}
int taint_check_sink(TaintGraph*tg,int var_id,Location loc,Issue*out){if(!tg||!out)return 0;if(var_id>=0&&var_id<tg->nvars&&tg->vars[var_id]&&tg->vars[var_id]->is_tainted){int source=tg->vars[var_id]->source;const char*src_str="unknown";switch(source){case TS_USER_INPUT:src_str="user input";break;case TS_FILE_READ:src_str="file read";break;case TS_NETWORK:src_str="network";break;case TS_ENV:src_str="environment variable";break;case TS_ARGV:src_str="argv";break;case TS_SYSTEM:src_str="system call";break;default:break;}code_scan_snprintf(out->msg,sizeof(out->msg),"Tainted data from %s reaches sink at line %d:%d",src_str,loc.line,loc.col);out->sev=SEV_ERROR;out->cat=CAT_SECURITY;return 1;}return 0;}
int taint_track_to_sink(TaintGraph*tg,int var_id,Location*path,int*path_len){*path_len=0;return 0;}
void taint_dump(TaintGraph*tg){if(!tg)return;code_scan_printf("TaintGraph: %d vars, %d flows\n",tg->nvars,tg->nflow);for(int i=0;i<tg->nvars;i++){if(tg->vars[i])code_scan_printf("  var%d: %s tainted=%d src=%d sanitized=%d\n",i,tg->vars[i]->name,tg->vars[i]->is_tainted,tg->vars[i]->source,tg->vars[i]->is_sanitized);}}
void taint_free(TaintGraph*tg){if(!tg)return;for(int i=0;i<tg->nvars;i++)if(tg->vars[i])free(tg->vars[i]);free(tg->vars);for(int i=0;i<tg->nflow;i++)free(tg->flow[i]);free(tg->flow);free(tg->sinks);free(tg);}
