/* Code-Scan Static Analyzer - Copyright (C) 2026 XPDevs. All rights reserved. */
#include "code_scan.h"
#include "walker.h"
void walker_init(Walker*w){memset(w,0,sizeof(*w));w->dir_cap=64;w->dirs=calloc(w->dir_cap,sizeof(char*));w->file_cap=1024;w->files=calloc(w->file_cap,sizeof(char*));w->recursive=1;w->max_depth=64;w->follow_symlinks=0;w->filter=walker_default_filter;w->ignore_cap=32;w->ignore_dirs=calloc(w->ignore_cap,sizeof(char*));w->nignore=0;w->ignore_patterns=NULL;w->npatterns=0;}
void walker_add_dir(Walker*w,const char*path){if(w->ndirs>=w->dir_cap){w->dir_cap*=2;w->dirs=realloc(w->dirs,w->dir_cap*sizeof(char*));}w->dirs[w->ndirs++]=code_scan_strdup(path);}
void walker_add_ignore(Walker*w,const char*dir){if(w->nignore>=w->ignore_cap){w->ignore_cap*=2;w->ignore_dirs=realloc(w->ignore_dirs,w->ignore_cap*sizeof(char*));}w->ignore_dirs[w->nignore++]=code_scan_strdup(dir);}
void walker_set_filter(Walker*w,FileFilter f){w->filter=f;}
int walker_default_filter(const char*path){return code_scan_is_source_file(path);}
static int walker_should_skip(Walker*w,const char*name){for(int i=0;i<w->nignore;i++){if(strcmp(name,w->ignore_dirs[i])==0)return 1;}if(strcmp(name,".")==0||strcmp(name,"..")==0)return 1;if(strcmp(name,".git")==0||strcmp(name,".svn")==0||strcmp(name,".hg")==0)return 1;if(strcmp(name,"node_modules")==0||strcmp(name,"__pycache__")==0)return 1;return 0;}
static void walker_walk_dir_r(Walker*w,const char*path,int depth){if(depth>w->max_depth)return;DIR*dir=opendir(path);if(!dir)return;struct dirent*entry;while((entry=readdir(dir))!=NULL){if(walker_should_skip(w,entry->d_name))continue;char*full=code_scan_concat(path,"/");char*full2=code_scan_concat(full,entry->d_name);free(full);if(!full2)continue;struct stat st;int stat_result;if(w->follow_symlinks)stat_result=stat(full2,&st);else stat_result=lstat(full2,&st);if(stat_result!=0){free(full2);continue;}if(S_ISDIR(st.st_mode)&&w->recursive){walker_walk_dir_r(w,full2,depth+1);}else if(S_ISREG(st.st_mode)){if(w->filter&&w->filter(full2)){if(w->nfiles>=w->file_cap){w->file_cap*=2;w->files=realloc(w->files,w->file_cap*sizeof(char*));}w->files[w->nfiles++]=full2;w->total_files++;w->total_size+=(int)st.st_size;}else{w->skipped_files++;}}else{free(full2);}}closedir(dir);}
void walker_walk(Walker*w){for(int i=0;i<w->ndirs;i++){walker_walk_dir_r(w,w->dirs[i],0);}}
void walker_free(Walker*w){if(!w)return;for(int i=0;i<w->ndirs;i++)free(w->dirs[i]);free(w->dirs);for(int i=0;i<w->nfiles;i++)free(w->files[i]);free(w->files);for(int i=0;i<w->nignore;i++)free(w->ignore_dirs[i]);free(w->ignore_dirs);memset(w,0,sizeof(*w));}
